- Sources/NIOHTTP2/HTTP2Parser.swift
- Sources/NIOHTTP2/NGHTTP2Session.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
Long-lived connections that have many inactive streams would cause
crashes. Crashes are, in my professional opinion, less than ideal
when they occur under expected usage cases.
Modifications:
- Fixed an inverted boolean check that would discard only *active*
streams.
- Added tests.
Result:
Fewer crashes, better software.
> Correctly discard only inactive streams.

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2Parser.swift
- Sources/NIOHTTP2/NGHTTP2Session.swift
- Tests/NIOHTTP2Tests/BasicTests+XCTest.swift
- Tests/NIOHTTP2Tests/BasicTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
We shouldn't just crash if the client sends bad magic.
Changes:
Send an error through the pipeline instead of crashing on bad client
magic.
Result:
fewer crashes
> don't crash when client sends bad magic

- NOTICE.txt
see also: https://github.com/http2jp/hpack-test-case/issues/27
Motivation:
We should attribute all external code/data we make use of, even in unit
tests.
Modifications:
Added hpack-test-case to NOTICE.txt
Result:
More attribution
> add hpack-test-case to NOTICE.txt

- Tests/NIOHPACKTests/HuffmanCodingTests.swift
Motivation:
When tests are run with sanitizers, in docker etc it's important to
disable timing sensitive tests.
Modifications:
make it possible to disable timing sensitive tests
Result:
swift-nio-release-tools happier
> make it possible to disable timing sensitive tests

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
The documentation previously stated that `createStreamChannel` returns an "`EventLoopFuture` that completes with the new channel", where in reality the method returns `Void` and you instead supply an `EventLoopPromise` that is succeeded with the new activated channel. This PR removes the `returns:` line from the documentation comment.
> Removes wrong return type documentation

- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
nghttp2 changed the error code it returns when the server sends a GOAWAY.
It's now `.cancelled` instead of `.refusedStream`.
Modifications:
Don't require a specific error code in the tests, just require that an
error matching the expected stream ID occurred.
Result:
Tests will pass on nghttp2-1.34.0.
> Fix tests on nghttp2-1.34.0

- Sources/NIOHTTP2/NGHTTP2Session.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
Due to nghttp2's weird data provider model, all trailers go through a
similar send path as data frames. This includes the fact that the data
sender can go "idle". If the data sender is idle, and the user sends
trailers, we don't bother to tell nghttp2 to ask us for more data,
so the trailers sit there forever, feeling sad.
Modifications:
- Correctly restart the data provider when sending data.
Result:
Trailers will be emitted when the stream is idle.
Resolves #24.
> Trailers sent on idle streams deserve to be sent too.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
Child channels should not activate before their parents.
Modifications:
Delay activation if the parent channel is not currently active.
Activate during channelActive, if needed.
Result:
Easier to start HTTP/2 requests
Resolves #26
> Correctly activate child channels.

- Sources/NIOHTTP2/HTTP2Parser.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
By initializing the handler in the handlerAdded hook, HTTP2Parser supports
being added dynamically in a channelRead event, after the channel has sent
the channelActive event.
> Initialize HTTP2Parser handler in the handlerAdded event hook.

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
Motivation:
The documentation for creating a new stream channel didn't indicate
whether the user had to do any cleanup on the multiplexer once a stream
was no longer in use.
Modifications:
Added a note to the documentation indicating that no additional action
is required by the user beyond closing the stream.
Result:
The documentation is less ambiguous.
> Clarify cleanup docs for stream channel creation

- docker/Dockerfile
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.yaml
- scripts/test_h2spec.sh
Motivation:
When we get around to it we should aim for our example server to pass
h2spec with flying colours. We aren't there yet, but it's helpful to
be able to run h2spec easily.
Modifications:
Add a docker-compose recipe for running h2spec.
Result:
It'll be easier to run h2spec.
> Add Dockerfile to run h2spec.

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2ConcurrentStreamsHandler.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Sources/NIOHTTP2/NIOHTTP2FlowControlHandler.swift
- Sources/NIOHTTP2Server/main.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests.swift
- Tests/NIOHTTP2Tests/FlowControlHandlerTests.swift
- Tests/NIOHTTP2Tests/HTTP2ConcurrentStreamsHandlerTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/ReentrancyTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
Code should compile and have the latest NIO 2 API.
Modifications:
- rename `ctx` to `context`
Result:
compiles again
> update to latest NIO 2 code

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2ConcurrentStreamsHandler.swift
- Sources/NIOHTTP2/HTTP2Frame.swift
- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Sources/NIOHTTP2/NIOHTTP2FlowControlHandler.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/FlowControlHandlerTests.swift
- Tests/NIOHTTP2Tests/HTTP2ConcurrentStreamsHandlerTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/ReentrancyTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
As discussed in our HTTP/2 types manifesto, it is helpful to run more
metadata through the HTTP/2 pipeline. This makes it easier to write
ChannelHandlers that fully participate in the HTTP/2 state machine
while avoiding needing to too tightly couple the handlers.
Modifications:
- Added new HTTP/2 pipeline data types.
- Removed HTTP2Frame.FrameFlags, moved flags into relevant payloads.
Result:
Right now, not much. All tests pass with new payload types. The full
data path rewrite will follow in a separate patch, as this one is large
enough.
> New HTTP/2 currency types.

- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/ReentrancyTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
NIO has made EmbeddedChannel operations throwing. We need to handle that.
Modifications:
- Added assertNoThrowWithValue around all EmbeddedChannel operations.
- Suppressed some throwing errors after the assertNoThrowWithValue.
Result:
Compiles again.
> Handle EmbeddedChannel throwing.

- Sources/NIOHPACK/HPACKDecoder.swift
- Sources/NIOHPACK/HPACKHeader.swift
- Sources/NIOHPACK/HuffmanCoding.swift
- Sources/NIOHPACK/RingBufferView.swift
- Sources/NIOHPACK/StringRing.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHPACKTests/IntegerCodingTests.swift
Motivation:
Code should be able to compile.
Modifications:
- Add necessary force-unwraps to ByteBufferViews.
- Remove use of now-dead HTTPHeaders storage and indices API.
Result:
No compile errors.
> Clean up new NIO breaking changes.

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2Stream.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Sources/NIOHTTP2Server/main.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
Motivation:
When we spiked out these codecs we were missing a number of error handling
paths, which meant that erroneous input would lead to crashes. While we
don't expect these handlers to have to face that kind of input, we should
still aim to tolerate it where doing so is reasonable.
Modifications:
- Replaced all force unwraps and preconditions with throwing.
Result:
Fewer crashes on bad input.
> Remove crashers from HTTP2ToHTTP1Codecs.

- Package.swift
This package is currently incompatible with `swift-nio-ssl` and `swift-nio-extras` since it relies on `branch("master")` and the other packages rely on the convergence tag. This PR updates this package to also rely on the convergence tag.
> depend on swift-nio 2.0.0 convergence

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2Server/main.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
PRIORITY frames aren't really sent on a single stream, so we shouldn't
attempt to deliver them to the child channels. Instead, we deliver them on
the parent channel.
Modifications:
Moved PRIORITY frames to the parent channel.
Result:
Less confusion about where PRIORTY frames go
> Deliver PRIORITY frames to the parent stream.

- Sources/NIOHPACK/HPACKDecoder.swift
- Sources/NIOHPACK/HPACKErrors.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
Motivation:
RFC 7541 is pretty clear that index 0 is no bueno in the indexed
header representation, so we should forbid it.
Modifications:
- Detected attempts to decode index 0.
Result:
Index 0 is now forbidden.
> Refuse to decode indexed header with index 0.

- Sources/NIOHTTP2/OutboundFlowControlBuffer.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests+XCTest.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
Motivation:
When setting the stream window size for a stream which had data but
couldn't write it (because of a zero window size) the stream would be
marked as flushable. Setting the window size to zero again would not
mark it as unflushable. On the following window (non-zero) resize it
would be marked as flushable again. However, since this is preceeded by
an assertion that it wasn't already marked as flushable it would cause a
crash.
Modifications:
- Mark the stream as unflushable if it previously had data which it
couldn't write.
Result:
Fewer crashes
> Remove flushability of streams when stream window size is set to zero.

- Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2ConnectionStateChange.swift
- Sources/NIOHTTP2/OutboundFlowControlBuffer.swift
- Sources/NIOHTTP2/OutboundFrameBuffer.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests+XCTest.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
When the remote peer changes SETTINGS_INITIAL_WINDOW_SIZE, this change
affects the flow control window sizes of all existing streams (as though
they were created with this new initial window size). We should respect
those flow control changes.
Modifications:
- Propagated changes in SETTINGS_INITIAL_WINDOW_SIZE.
- Made NIOHTTP2ConnectionStateChange internal.
- Added support for changing initial window size.
Result:
SETTINGS frames that change initial window size now work properly.
> Respect changes to INITIAL_WINDOW_SIZE in outbound buffer.

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
Motivation:
Receiving a CONTINUATION frame at the wrong stage of a connection is
a PROTOCOL_ERROR, but out of an abundance of caution we were categorising
it as an INTERNAL_ERROR. We should be more confident about our error
categories.
Modifications:
- Changed INTERNAL_ERROR to PROTOCOL_ERROR.
- Added a test for this error case.
Result:
More confidence, more style, more pizazz.
> Be emphatic about remote peers making mistakes.

- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
Motivation:
We mustn't allow CONTINUATION frames to be sent on invalid stream IDs.
Modifications:
- Police that the CONTINUATION frame raw stream ID matches the previous
frame's raw stream ID.
Result:
Better conformance to the RFC
> CONTINUATION frames must be for the correct stream.

- Sources/NIOHTTP2/ConnectionStateMachine/HasLocalSettings.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2ConnectionStateChange.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2UserEvents.swift
- Sources/NIOHTTP2/InboundWindowManager.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
The StreamMultiplexer and StreamChannels are responsible for sending
WINDOW_UPDATE frames, but they were never told if the user changed the
value of SETTINGS_INITIAL_WINDOW_SIZE. They should be.
Modifications:
- Send user events when SETTINGS_INITIAL_WINDOW_SIZE changes.
- Use those window events to change the target window size in
HTTP2StreamChannel.
- Keep track of the last stream window size we knew.
Result:
Less chance of flow control mess.
> Correctly notify StreamMultiplexer of SETTINGS changes.

- Package.swift
- Tests/NIOHTTP2Tests/ReentrancyTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
EmbeddedChannel's API has changed a litle bit, we should update.
Modifications:
update
Result:
code will continue to work
> update to latest EmbeddedChannel API

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/OutboundFlowControlBuffer.swift
- Sources/NIOHTTP2/OutboundFrameBuffer.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest+XCTest.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests+XCTest.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
In the future we'll want to use PRIORITY frames to provide feedback on
how we emit data. Additionally, RFC 7540 forbids certain kinds of
PRIORITY frame, which right now we tolerate receiving. We can design a
minor PRIORITY shim to ensure that we have a code path for PRIORITY data
to be passed around, and then use this shim to enforce RFC 7540's
requirements.
Modifications:
- Added support for PRIORITY frame data inbound.
- Enforce that frames may not establish self-dependency.
Result:
Better policing of RFC 7540 constraints.
> Basic PRIORITY frame validation.

- README.md
Motivation:
swift-nio-http2 is no longer in beta and does no longer require nghttp2.
We should state that.
Modifications:
Remove outdated and wrong information from the readme.
Result:
Fewer lies in the documentation.
> remove outdated information from readme

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
The stream multiplexer was incorrectly eating channelActive on its own
channel, and failing to pass them on to subsequent channel handlers, if
there were any.
Modifications:
- Passed channelActive on from stream multiplexer.
Result:
Easier to handle things on the parent channel.
Resolves #75.
> Forward channelActive from stream multiplexer.

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
RFC 7540 requires that the END_STREAM bit be set on a HEADERS frame that
sends trailers. We should enforce that.
Modifications:
- Require that the END_STREAM bit is set on trailers.
Result:
We reject more incorrect flows.
> Require END_STREAM to be set on trailers.

- Sources/NIOHPACK/DynamicHeaderTable.swift
- Sources/NIOHPACK/HPACKEncoder.swift
- Sources/NIOHPACK/HeaderTables.swift
- Sources/NIOHPACK/IndexedHeaderTable.swift
While investigating performance of HTTP/2 I noticed a substantial number
of allocations occuring in a hot loop in header compression. Specifically
I set up a simple harness that encoded headers 100 times, and then ran
that harness 10k times. This harness ended up performing 17 million
allocations, which is frankly a bit too high!
The fact that the number of allocations was in the millions suggested that
we were allocating some resources per header encode. That's not good:
assuming the target `ByteBuffer` is big enough we should not need to
perform new allocations to encode headers.
The allocations came from two places. Firstly, we were allocating in the
`HeaderTableStorage.indices(matching:)` function. This was because that
operation was returning a lazy collection, which required …
> Decrease allocations in encode loop.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingPushPromiseState.swift
- Sources/NIOHTTP2/HPACKHeaders+Validation.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
RFC 7540 forbids uppercase characters in header field names, but we
currently allow them. We shouldn't.
This is the first in a series of patches that will validate header blocks
when reasonable. As a result, it seems larger than necessary, as it adds
a bunch of scaffolding for extending with further validation code.
Modifications:
- Added header field validation scaffolding.
- Validates that header field names do not contain uppercase chars.
- Allows sending RST_STREAM frame before stream setup.
Result:
Better header field validation.
> Validate no uppercase characters in header field names.

- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
Zero length SETTINGS frames are permitted by RFC 7540 but the frame
parser currently throws a FRAME_SIZE_ERROR.
- Allow zero length SETTINGS frames to be parsed
- Added a test
Parsing zero length SETTINGS frames don't throw an error.
> Allow zero length SETTINGS frames to be parsed.

- Sources/NIOHTTP2/HPACKHeaders+Validation.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
RFC 7540 requires that HTTP/2 pseudo-headers must be first in a HTTP/2
header block, and must occur before any regular headers. We should enforce
that requirement.
Modifications:
- Added checking that pseudo-headers are first in a header block.
Result:
Better RFC 7540 validation.
> Enforce pseudo-headers must be first in a header block.

- Sources/NIOHTTP2/HPACKHeaders+Validation.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
RFC 7540 does not allow empty :path pseudo-headers. We should police this.
Modifications:
- Added a check that :path isn't empty.
Result:
Better RFC 7540 validation.
> Forbid empty :path headers.

- Sources/NIOHTTP2/HPACKHeaders+Validation.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
RFC 7540 forbids the use of connection-specific header fields, except for TE sent
with the value "trailers". We should police that.
Modifications:
- Added extra policing around regular header fields.
Result:
Better validation
> Validate that connection-specific headers aren't sent.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
When we're validating that settings are in their bounds, we should probably endeavour to
express those bounds correctly.
Modifications:
- Fixed the bounds checks on SETTINGS_INITIAL_WINDOW_SIZE and SETTINGS_MAX_FRAME_SIZE.
- Added regression tests.
Result:
Better correctness.
Resolves #96
> Resolve off-by-one errors in settings bounds.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingDataState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingDataState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingHeadersState.swift
- Sources/NIOHTTP2/ContentLengthVerifier.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- scripts/test_h2spec.sh
Motivation:
RFC 7540 requires that compliant specifications emit errors if content-length has been incorrectly
set. We should have this behaviour by default, though we should allow it to be disabled if necessary.
Modifications:
- Added content-length checking.
- Added flag to disable content-length checking.
Result:
Better RFC 7540 compliance.
Passing h2spec.
> Police correct content-length headers.

- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingGoAwayState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingGoawayState.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
We would previously error if clients emitted a GOAWAY frame that had
a last stream ID set to the max value. This is a bit unnecessary, not
least given that we emitted those frames ourselves! In fact, this error
would mask real server protocol errors if we hit them.
Modifications:
- Allowed max stream ID as the last stream ID.
- Wrote a test to verify this.
Result:
Fewer unnecessary protocol errors.
Resolves #101.
> Allow maxStreamID to be used in GOAWAY by either peer.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
Motivation:
When benchmarking the HTTP/2 implementation I noticed that we were
performing a large number of CoW operations on the Dictionary that backs
the ConnectionStreamState structure: specifically, once per frame sent or
received.
This is substantial and unnecessary allocation overhead that drags down
the performance of the program, sprays the heap with small allocations, and
generally just leads to nasty performance costs with no gain.
Sadly, this turns out not to be the easiest CoW to get rid of, because
the ConnectionStreamState structure is stored in associated data on the
connection state machine state enumeration. This means that our usual tricks
for avoiding the CoW (such as swap()) no longer work.
The only solution is to add a new state that corresponds to no state at all
so …
> Remove unnecessary state CoWs.

- Sources/NIOHTTP2/HTTP2FrameParser.swift
Motivation:
As noted in #105, I spotted that we were heap-allocating an array
when parsing the frame header. That heap allocation isn't necessary, we
can just write directly into an Int, which should save us some heap spray.
Modifications:
- Rewrote code to avoid heap allocating array and instead to use Int.
- Elided some bounds checks by using an unsafe pointer, since I was
already here and it saved about 1% performance in a hot loop.
Result:
Fewer heap allocations on the hot code path.
Resolves #105
> Avoid unnecessary heap allocation when parsing frame headers.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingWindowUpdateState.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
RFC 7540 Section 6.9: "WINDOW_UPDATE can be sent by a peer that has sent
a frame bearing the END_STREAM flag.  This means that a receiver could
receive a WINDOW_UPDATE frame on a "half-closed (remote)" or "closed"
stream. A receiver MUST NOT treat this as an error (see Section 5.1)."
Previously WINDOW_UPDATE frames received in this state would be treated
as an error.
Modifications:
- Allow frames to be ignored if they are for a stream which has been
closed.
- Add a test to verify WINDOW_UPDATE on a closed stream.
- Update tests which relied on a stream error in this case.
Result:
More compliant code.
> Ignore WINDOW_UPDATE on closed streams.

- Sources/NIOHTTP2/HTTP2Frame.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
Motivation:
Anything that passes through a NIO pipeline in high volume that is not special-cased by NIOAny
needs to have careful attention paid to its size. This is because if it's more than 3 64-bit words
wide (24 bytes), it will need to be heap-allocated to be stuffed into the Any case of the NIOAny.
Sadly, HTTP2Frame was 44 bytes wide: altogether too wide for the pipeline. This was forcing heap
allocations each time a frame was sent or received in the pipeline, which is not so good.
To avoid this problem we normally turn our data structures into a CoW box. We want to do that
here as well, but we need to be a bit careful. Many parts of the code access the `streamID` field
frequently, and placing the stream ID into the CoW box will slow those accesses down by requiring a
memory load from …
> Provide a CoW box for large HTTPFrame.FramePayload cases.

- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
Motivation:
When synthesising data frames we try to emit the flow controlled length of the entire real
data frame on the first synthetic frame. This allows us to correctly police the window management
of that frame, while still synthesising frames.
However, @glbrntt spotted that we were incorrectly repeatedly counting the flow controlled length
of a partial frame. A patch that had been previously added to ensure we only counted it once was
not working correctly.
Modifications:
- Adjusted the location of the call to flowControlledLength.
Result:
Correct accounting of flow controlled length
> Avoid double-counting of flow controlled length of synthesised data frames

- Sources/NIOHPACK/HPACKDecoder.swift
Motivation:
I was seeing frequent reallocations of the headers array as it
resized during decoding.
Modifications:
Reserve capacity for at least 16 HPACK headers during decoding.
Result:
Fewer reallocations at the cost of allocating more than we might need.
> Reserve capacity when decoding HPACK headers

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
Motivation:
When users create a child channel and want to get hold of it,
they will pass a promise to createStreamChannel. This promise
will force a call to map{} and a call to cascade(), both of
which heap allocate. We don't need to have these heap allocations,
and they're easily removed, so we should.
Modifications:
Manually cascade the result.
Result:
Slightly fewer heap allocations in some workloads.
> Avoid 8 heap allocations on child channel creation

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
Users who create stream channels may end up deciding not to use them
and throw them away. We should tolerate this, instead of hanging.
Modifications:
- Rewrote the state management to properly isolate states.
- Allow instant-close when the network hasn't seen the stream.
Result:
Close is faster and works better.
> Allow closing idle StreamChannels.

- Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2ConnectionStateChange.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
If the remote peer changes SETTINGS_MAX_CONCURRENT_STREAMS we should ensure that we don't
subsequently violate those bounds.
Modifications:
- Plumb in the SETTINGS_MAX_CONCURRENT_STREAMS change.
Result:
SETTINGS_MAX_CONCURRENT_STREAMS works better
> Pass changes in SETTINGS_MAX_CONCURRENT_STREAMS to outbound buffer.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
Our existing model for working out whether a stream channel is active is
a bit too ad-hoc. We "activate" a stream channel once the initializer
has completed so long as the parent channel is active. This approach
is basically reasonable, but it makes it a bit hard to handle stream
closure.
Specifically, in the client case a stream channel may be "active" but
have never sent a frame. In this case we can (and must) close the stream
without sending a frame if the user requests closure. This means we
need to know whether or not the stream is actually open from the
perspective of the parent channel.
Modifications:
- Added new notifications about whether the stream is active on the
network
- Enhanced the stream channel to be more clear about its state.
- Wrote some new tests.
- Fixed …
> Better manage stream channel activation.

- Sources/NIOHTTP2/OutboundFrameBuffer.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest+XCTest.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
Motivation:
We recently spotted that in an edge case it was possible for the
outbound frame buffer to incorrectly believe that a flushed frame was in
fact not flushed, and to refuse to give it up until it had encountered a
flush point. This could happen if the frame was flushed but buffered in
the concurrent streams buffer, and was then moved to the flow control
buffer but could not be emitted.
Modifications:
Correctly marked such frames as flushed.
Result:
We won't wedge frames in the buffer.
> Correctly persist frame flush status.

- docker/docker-compose.1804.50.yaml
Motivation:
Warnings are bad, let's make them errors.
Modifications:
enable `-warnings-as-errors`
Result:
Fewer warnings.
> enable warnings as errors

- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_request_response.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- docker/docker-compose.1804.50.yaml
Motivation:
Previously the HTTP2StreamChannel forwarded all frames to the parent
Channel by way of the abstract Channel existential API. While this was
straightforward, it added unnecessary overhead due to the extra pipeline
steps and the extra indirection of the types providing an inlining
barrier.
Given that in #116 we gave the HTTP2StreamChannel a reference to its
parent multiplexer, we may as well take advantage of this and allow
direct calls from the stream channel into the multiplexer.
Modifications:
Avoided calls to parent.write and parent.flush.
Replaced them with a new interface.
Result:
Slightly better performance.
> Remove indirection between channel and multiplexer

- docker/Dockerfile
- docker/docker-compose.1804.50.yaml
motivation: now that swift has official docker images, use them instead of the homebrewed one
changes: refactor docker file to use swift:version instead of ubuntu:version
> use official docker image

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests.swift
Motivation:
Stream channels don't get closed when the parent channel closes. This
can lead to some unexpected behaviour for users.
Modifications:
Call receiveStreamClosed on stream channels in the multiplexer when
reciving channelInactive. Added a test to verify the stream is closed.
Result:
Stream channels will be closed when the parent channel is closed.
> Close stream channels when the parent channel becomes inactive

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
The HTTP2StreamMultiplexer currently passes frames from child streams
through to the rest of the pipeline, and does the same with flushes.
Because HTTP2 is multiplexed, it is highly likely that in any
channelRead cycle multiple child channels will make sufficient progress
to want to flush their results. This means we can end up with multiple,
redundant, flush calls.
It would be better in general to try to reduce the amount of flushing
necessary to no more than once per channelRead cycle.
Modifications:
- Keep track of the channelRead cycle and where we are in it.
- Avoid flushing when we can expect a channelReadComplete.
- Flush on channelReadComplete if necessary.
Result:
Fewer flushes, better performance under high read load.
> Coalesce flushes during the read cycle.

- Sources/NIOHTTP2/ConcurrentStreamBuffer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/OutboundFlowControlBuffer.swift
- Sources/NIOHTTP2/OutboundFrameBuffer.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest+XCTest.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
While having outbound buffers is necessary, it's pretty important to
clear then when the connection is closed, or the promise will get
leaked. In this case, leaking the promise is usually pretty dang bad,
and tends to cause awkward things like crashes.
Modifications:
- Added hooks to invalidate the CompoundOutboundBuffer.
- Called those hooks in handlerRemoved, where there is no reentrancy
risk.
Result:
Less risk of runtime crash.
> Drop buffered outbound frames when closing.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/StreamChannelList.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
Currently swift-nio-http2 is extremely naive with its use of
channelReadComplete calls in HTTP2StreamChannel, firing one
channelReadComplete call per frame read. In high frame load cases this
leads to a lot of excessive channelReadComplete traffic, which can cause
unnecessary time spent in flush calls.
We should try to minimise the amount of time we spend on this
bookkeeping and save the CPU cost.
Modifications:
- Store a linked-list of HTTP2StreamChannels that need to have
channelReadComplete fired on them.
- Fire channelReadComplete based on this linked list.
Result:
Moderate improvement in performance in high-throughput workloads.
> Minimise channelReadComplete traffic.

- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
RFC 7540 is not particularly clear on whether the server is required to
send PUSH_PROMISE frames before or after the HEADERS frame, or whether
both are acceptable. We took a somewhat hard-line approach by asserting
that PUSH_PROMISE could only be sent after the server sent HEADERS, but
we've now caught at least one notable implementation in the wild doing
something different (nghttp2).
Given that there's no clear normative language pointing in either
direction, we should consider being a bit more lenient and allowing
both.
Modifications:
- Updated the stream state machine to allow pushes on a locally-idle
stream.
Result:
Servers can send PUSH_PROMISE before they have sent HEADERS.
Resolves #144.
> Allow servers to send PUSH_PROMISE before HEADERS.

- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
Motivation:
Previously, the H2to1 codec would crash if for example a push promise
came by.
Modifications:
Instead of crashing, ignore the frames without equivalent.
Result:
Fewer crashes.
> ignore frames that don't have a HTTP/1 equivalent

- docker/Dockerfile
Motivation:
In Dockerfiles it's important to re-run apt-get update in every step
because otherwise the apt-get install may fail.
Modification:
Add apt-get update everywhere.
Result:
CI will hopefully work again.
> [nio-http2-0.2, nghttp2]add apt-get update to the Dockerfile

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Not sure if you are still interested in patches for the nghttp2 support branch. Some people might be brave enough to be still using it... ;)
I noticed that stale/disconnected connections never fail/disconnect the child channels. The reason seems to be that the multiplexer does not forward `channelIncactive` events. This PR fixes this.
If you _really want_ I can add an test for this...
> [nghttp2] Forward `channelInactive` events to the child channels.

- docker/docker-compose.1804.50.yaml
Motivation:
We regressed 4 allocations in the security update
https://github.com/apple/swift-nio-http2/security/advisories/GHSA-jchv-x857-q8fq
. Four allocations are a great tradeoff for a number of security
vulnerabilities fixed but we need to raise the limits accordingly.
Modifications:
Raise the limits to the new limit so tests can pass again.
Result:
PRs can pass again and master should build again.
> fix allocation counter limits

- README.md
Motivation:
We should always recommend secure versions.
Modifcation:
Recommend `from: "1.5.0"`.
Result:
People will hopefully run more secure software.
> recommend secure version

- Sources/NIOHPACK/HPACKHeader.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
HTTP/2 is mostly just HTTP(/1) semantics with streams on a new wire
protocol. However, there are certain things that are legal in HTTP/1 but
which are illegal in HTTP/2.
Modification:
Accept more of those messages and transform them into their HTTP/2
equivalent.
Result:
- Easier to write HTTP/2 clients & servers in NIO.
- fixes #152
> accept more valid-in-HTTP/1 but invalid-in-H2 messages

- Package.swift
Having correct dependencies is important but `swift-nio-http2` requires NIO 2.3.0 or better but claimed it could do with NIO 2.0.0.
Bump the NIO requirement to 2.3.0.
Dependencies more correct.
> fix dependencies: require NIO 2.3.0

- docker/Dockerfile
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.51.yaml
motivation: support swift 5.1
changes:
* add docker compose file for swift 5.1, will add CI job once merged
* update swiftformat version to 0.40.12
* use more standard dockerfile setup
> swift 5.1 docker setup

- Package.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHPACKTests/HuffmanCodingTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
- docker/docker-compose.1804.50.yaml
Motivation:
All other NIO repositories now have namespaced ChannelOptions.
Modifications:
Namespace the ChannelOptions and fix the deprecations resulting from namespacing swift-nio's ChannelOptions (and other 2.9.0 changes).
Results:
Fewer warnings.
> namespace ChannelOptions & fix deprecations

- Sources/NIOHPACK/HPACKEncoder.swift
- Sources/NIOHPACK/IndexedHeaderTable.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
- Tests/NIOHPACKTests/HeaderTableTests+XCTest.swift
- Tests/NIOHPACKTests/HeaderTableTests.swift
Motivation:
In many cases it's necessary to be able to do HPACK table lookups to
find only a matching header field name, when it isn't going to be
possible to use a fully indexed header. For example, when using
nonIndexable header fields you cannot use an indexed field value, so
there is no point looking at all the header field values anyway.
While we technically supported this, there were two wrinkles. The first
was that if you attempted to search for a header field without any care
for its name, we'd actually only search the static table, missing
anything added into the dynamic table, which is pretty stupid.
The second issue was that nonIndexable header fields did extra
unnecessary work. This is because we asked the header table to search
for an exact match, but then disregarded whether …
> Fix partial table lookups.

- Sources/NIOHPACK/HPACKHeader.swift
Motivation:
We have a slow path in compareCaseInsensitiveASCIIBytes. On the server
this path will never be hit as to hit it requires having a
non-contiguous String, so we really really want the compiler to use all
its inlining smarts on the fast path instead. Currently it does, but as
Sequence.elementsEqual is inlinable we need to be sure that doesn't
change.
Modifications:
Force the slow path not to be inlined.
Result:
Guarantees about good inlining.
> Force slow path header comparison to not inline.

- Sources/NIOHTTP2PerformanceTester/Benchmark.swift
- Sources/NIOHTTP2PerformanceTester/HPACKHeaderDecodingBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/HPACKHeaderEncodingBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/HuffmanDecodingBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/HuffmanEncodingBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/main.swift
- Tests/NIOHPACKTests/HuffmanCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HuffmanCodingTests.swift
Motivation:
Having benchmarks for the HPACK encoder and decoder gives us betterinsight into their performance.
While we're here, we can move the Huffman benchmarks out of the unit tests and into the benchmark suite.
Modifications:
Added encoder, decoder, and huffman benchmarks.
Result:
Better performance numbers.
> Add HPACK and Huffman benchmarks.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingRstStreamState.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
The HTTP/2 RFC does not explicitly forbid sending more than one
RST_STREAM for the same stream. Given that we have seen this behaviour
in the wild we are going to ignore any additional RST_STREAMs.
A further indicative that this is the right call is that the RFC
explicitly mentions that sending RST_STREAMs in the idle state is not
acceptable.
Modifications:
Ignore RST_STREAM frames for streams in the closed state.
Result:
More compatibility.
> tolerate multiple RST_STREAMs for same stream

- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
Newer Swift compilers warn about implicitly tupling the payload of an
enum case whilst pattern matching.
Modification:
Stop using implicit tupling.
Result:
No warnings on newer Swift compilers.
> fix new warnings in very new Swift compilers

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
Frames that close a stream may consume some of the connection window. We
were not correctly accounting for that in the code, which meant that
frames that carried END_STREAM would not notify the stream multiplexer
that they had consumed connection window space. In the worst cases this
could lead to resource starvation due to consumption of this window
without causing us to emit new WINDOW_UPDATE frames.
Modifications:
StreamClosedEvents should be followed by flow control change events.
Result:
We will correctly update the connection window when a stream is closed.
Resolves #173.
> Account for window size of stream closing frames

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
swift-nio-http2 commit hash: 85d5cea3f9134a242ad4baaa3a4af1ff080a3f81
Context:
Address the issue #151. Update BadStreamStateTransition to have a property with the stream state when the error happened. This public steam state is a enum without any associated values.
Also update some unit test functions to return an optional error. 
% swift --version
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0
> Issue #151 Update BadStreamStateTransition to have stream state

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
Previously, if we failed in the stream channel initialiser and the
stream channel was closed before finishing the stream channel
initialiser, we would crash on an assertion because `closedWhileOpen`
correctly asserted that it has nothing to do and shouldn't be called.
Modification:
Apart from `.idle` also stop calling `closedWhileOpen` in `.closed` and
`.localActive` because the network actually doesn't think this channel
is open.
Result:
- Fewer crashes
- fixes rdar://59342916
> stream channel initialiser: allow closed & failed

- Package.swift
- scripts/build_podspec.sh
- scripts/list_topsorted_dependencies.sh
- `SwiftNIOHTTP2` has a dependency on internal target `SwiftNIOHPACK` so validating the podspec was failing
- Updated the script to allow for the generation of both `SwiftNIOHTTP2.podspec` & `SwiftNIOHPACK .podspec`
- In `NIOHTTP2StreamChannel.swift`, it imports `NIOConcurrencyHelpers` which was not added as a dependency explicitly. Added the dependency which allowed the successful validation of the `SwiftNIOHTTP2` Pod. 
[SwiftNIOHTTP2](http://cocoapods.org/pods/SwiftNIOHTTP2)
[SwiftNIOHPACK](http://cocoapods.org/pods/SwiftNIOHPACK)
Newly created Pods from Release 1.9.1 - still need to add the other maintainers as Pod owners!
> Update build_podspec script & added SwiftNIOHPACK Pod

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests.swift
Motivation:
Applications might want to support H2 (when available) and HTTP1 (as a fallback).
The application logic should not change between the two versions of the protocol and the code to configure support for both the protocols is boilerplate and can be provided as an helper function.
Modifications:
This PR adds an helper function to configure HTTP1 or H2 pipelines according to the protocol negotiated by the TLS handler.
Result:
Applications that need to support clients using both HTTP1 and H2 can configure their channels by calling `configureCommonHTTPServerPipeline`, which should reduce the boilerplate they have to write.
> Added helper to configure HTTP1 or H2 accordingly to the negotiated protocol

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
This PR fixes https://github.com/apple/swift-nio/issues/1458 by marking the replacement method `public`. It also cleans up the ACL of the extensions in the file by moving the `public` to the function rather than the extension, as recommended.
> Mark Channel.configureHTTP2SecureUpgrade Public

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
Motivation:
Sometimes it's useful to be able to print out objects and see their
internal state. Somehow, HTTP2Handler can't do this.
Modifications:
Add a conformance to HTTP2Handler.
Result:
Awesome debugging output.
Now renders:
```
NIOHTTP2Handler(
stateMachine: HTTP2ConnectionStateMachine(state: NIOHTTP2.HTTP2ConnectionStateMachine.(unknown context at $1003b2c94).State.active(NIOHTTP2.HTTP2ConnectionStateMachine.(unknown context at $1003b27bc).ActiveConnectionState(role: NIOHTTP2.HTTP2ConnectionStateMachine.ConnectionRole.server, headerBlockValidation: NIOHTTP2.HTTP2ConnectionStateMachine.ValidationState.enabled, contentLengthValidation: NIOHTTP2.HTTP2ConnectionStateMachine.ValidationState.enabled, localSettings: NIOHTTP2.HTTP2SettingsState(currentSettingsValues: …
```
> Improve debugging output for HTTP2Handler.

- README.md
Motivation:
Linking to `CONTRIBUTING.md` directly would save readers some time if they'd like to navigate to this file while reading `README.md`.
Modifications:
No functional change, only `README.md` is updated.
Result:
The rendered `README.md` will have a direct link to `CONTRIBUTING.md`.
> Link to CONTRIBUTING.md in README.md

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests.swift
Make multiplexer's `targetWindowSize` configurable and use configurability when creating stream channels.
Motivation:
`targetWindowSize` constrains throughput. The default hardcoded `65535` is an unecessarily low limit that should be otherwise configrable. A `TODO` in the code stated as such.
Modifications:    
- In `HTTP2StreamMultiplexer`, responding to a `TODO` where stream multiplexer creates a stream channel, created a multiplexr stored property to be used which is set in the default initilaizer.
- In `HTTP2PipelineHelpers`, added versions of `configureHTTP2Pipeline(..)` and `configureCommonHTTP2ServerPipeline(..)` that require an `activeTargetWindow` arg.
Result:    
Clients, such as `GRPCClient`, can configure pipelines with targetWindowSizes to their liking.
> Make multiplexer's targetWindowSize configurable

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
Motivation:
Sometimes folks will want to print things about the HTTP2StreamChannel,
and we should give them the things we can safely get. We also may want a
shorter log for NIOHTTP2Handler as the standard description, with the
wall of text available in the debug description.
Modifications:
- Conform HTTP2StreamChannel to CustomStringConvertible
- Conform NIOHTTP2Handler to CustomDebugStringConvertible.
Result:
Even better debug info.
> Add debugging info to HTTP2StreamChannel too.

- Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
As Chrome has started GREASEing HTTP/2 settings and frames, we should
ensure that we have tests that explicitly validate that we tolerate
GREASEing these parameters.
A future version of swift-nio-http2 should start emitting GREASE as
well, but for now we'll satisfy ourselves with this.
Two relevant citations:
https://tools.ietf.org/html/draft-bishop-httpbis-grease-00
https://bugs.chromium.org/p/chromium/issues/detail?id=1083706
Modifications:
- Added a frame parser test
- Added a end-to-end settings test.
Result:
Validated that GREASE is tolerated.
> Explicitly test we tolerate GREASE.

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
As part of #202 we added support for configuring the target window size
of stream channels. That was plumbed through into outbound channels, but
we missed the inbound ones, meaning that this only really worked for
clients, not servers. That hardly seems fair!
Modifications:
Pass target window size to inbound channels too.
Result:
We can control target window size of inbound channels.
> Respect target window size on inbound channels.

- Package.swift
- Tests/NIOHPACKTests/HeaderTableTests.swift
Motivation:
The compiler team aren't fixing https://bugs.swift.org/browse/SR-12781
so I guess it's on us :(.
Modifications:
- fix missing "NIOFoundationCompat" dependency
- workaround https://bugs.swift.org/browse/SR-12781 by introducing extra
variables
Result:
compiles on 5.3
> workaround SR-12781

- Tests/NIOHPACKTests/HeaderTableTests.swift
- Tests/NIOHPACKTests/HuffmanCodingTests.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
- Tests/NIOHTTP2Tests/ConcurrentStreamBufferTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motiviation:
A few `#file` parameters have been forwarded to (now) `#filePath` ones.
Modification:
- silence the `#file`/`#filePath` warning by adding `(#file)` because we
can't forward them properly right now
(https://bugs.swift.org/browse/SR-12934). That's okay because even on
the Swift master branch, `#file` == `#filePath`.
Result:
No warnings in newer Swift compilers.
> fix warnings with newer Swift compilers

- .gitignore
- Tests/NIOHPACKTests/HeaderTableTests.swift
- Tests/NIOHPACKTests/HuffmanCodingTests.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
- Tests/NIOHTTP2Tests/ConcurrentStreamBufferTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
only works if done when _calling_ a function, not when defining one :|.
- https://github.com/apple/swift/pull/32445
- https://bugs.swift.org/browse/SR-12936
- https://bugs.swift.org/browse/SR-12934
- https://bugs.swift.org/browse/SR-13041
Modifications:
Silence #file to #filePath differently.
Result:
Hopefully at some point we get this working.
> forward #file to #filePath differently

- docker/Dockerfile
Motivation:
Ruby on Xenial is too old for the cocoapods downloader which jazzy uses.
Modifications:
Change Dockerfile to not install Jazzy on xenial.
Result:
Dockerfile will build again, but bionic or later is required for docs.
> Don't install Jazzy on Xenial

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
Motivation:
As part of the work in #214, HTTP2StreamID will need to be able to
tolerate not knowing its stream ID. For now this is not a problem, but
we should think about everywhere we use the stream ID and make sure we
have a solid principle in mind. This lays the groundwork for future
enhancements.
Modifications:
- Update HTTP2StreamChannel to hold an optional stream ID.
- Update interface to HTTP2StreamMultiplexer to tolerate closing
channels without stream IDs (we'll need it later).
- Move the "get a new stream ID" functionality to a method on
HTTP2StreamMultiplexer.
- Validate we behave correctly with optional stream IDs in the channel.
Result:
We can tolerate stream IDs being not present.
> Update HTTP2StreamChannel to tolerate nil stream ID.

- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
Motivation:
As part of the work in #214 we're going to need to update the
HTTP2ToHTTP1 codecs. These need to be replaced for the new channel
pipelines. The core of the logic will be identical in both cases, so
let's start by factoring that logic out into some nice standalone
objects that we can reuse.
Modifications:
- Pull out the base codecs into structures.
- Rewrite the main codecs in terms of these new structures.
Result:
Easier extension points.
> Refactor the codecs for extension.

- Sources/NIOHTTP2/HTTP2Frame.swift
- Sources/NIOHTTP2/HTTP2FrameConvertible.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
Motivation:
As part of #214 we need to make `HTTP2StreamChannel` generic over the type
of message it expects to read and write. This allows us to define an
`HTTP2StreamChannel` which uses `HTTP2Frame.FramePayload` as its
currency type, rather than `HTTP2Frame`.
Modifications:
- Make `HTTP2StreamChannel` generic over `Message` which is constrained
by conformance to `HTTP2FrameConvertible` and
`HTTP2FramePayloadConvertible`
- `HTTP2StreamChannel` now expects to read in `Message`s (as opposed to
`HTTP2Frame`s) and have `Message`s written in to it.
- Added typealiases for frame and payload based stream channels.
- Added support for the payload based channel in
`MultiplexerAbstractChannel` (although one can't be created yet).
Result:
We can create payload based stream channels.
> Make HTTP2StreamChannel generic over a message type

- Tests/LinuxMain.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKIntegrationTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKRegressionTests+XCTest.swift
- Tests/NIOHPACKTests/HeaderTableTests+XCTest.swift
- Tests/NIOHPACKTests/HuffmanCodingTests+XCTest.swift
- Tests/NIOHPACKTests/IntegerCodingTests+XCTest.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest+XCTest.swift
- Tests/NIOHTTP2Tests/ConcurrentStreamBufferTest+XCTest.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ControlFrameBufferTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameConvertibleTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/InboundWindowManagerTests+XCTest.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests+XCTest.swift
- Tests/NIOHTTP2Tests/ReentrancyTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/StreamChannelFlowControllerTests+XCTest.swift
- Tests/NIOHTTP2Tests/StreamIDTests+XCTest.swift
- scripts/generate_linux_tests.rb
Motivation:
To test deprecated functionality without a bunch of warnings, tests must
be marked as deprecated. This also needs to be bubbled up to anywhere
calling that test, such as in the generated linux test manifests.
Our script to generate the manifests currently doesn't support this and
as part of #214 we'll need to deprecate a few things while keeping their
tests.
Modifications:
- Pull in the latest version of the `generate_linux_tests.rb` script
from SwiftNIO.
- Re-run the script, since it includes some formatting changes too.
Result:
- When we deprecate functionality, we can deprecate the tests without
the generate manifests emitting warnings.
> Update the test generation script to allow for deprecated tests

- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
We have many test utilities for `HTTP2Frame` which predominantly make
assertions about the payload. As part of the work done for #214 we'll
need to make these assertions on the payload rather than the frame.
Modifications:
- Refactor `HTTP2Frame` test utilities to pull the payload assertions
into separate assertions on `FramePayload`
- `HTTP2Frame` assertions call through to the payload assertions
Result:
We can make assertions about payloads.
> Add test utilities for `FramePayload`s

- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
Motivation:
We added HTTP2FramePayload-to-HTTP1 codecs as part of #214 but are yet
to deprecate their HTTP2-to-HTTP1 counterparts.
Modifications:
- Deprecate `HTTP2ToHTTP1ClientCodec`
- Deprecate `HTTP2ToHTTP1ServerCodec`
- Deprecate tests containing them
- (We already have tests for HTTP2FramePayload-to-HTTP1 codecs)
Result:
HTTP2-to-HTTP1 codecs are deprecated
> Deprecate the HTTP2 to HTTP1 codecs

- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
We made a bunch of changes to resolve #214. We should add a test to
ensure we actually fixed the issue.
Modifications:
- Add a test verifying that we can write on streams in a different order
to the order in which we create them
- Add a corresponding test for frame-based streams verifying that the
first write on each stream must match the order in which the streams
were created
- Remove an unnecessary `throws` in the base HTTP2 to HTTP1 server codec
Result:
- No functionality change, just more tests.
> Verify payload-based stream channel fixes #214

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
NIO's backpressure management systems rely on catching calls to read()
in the ChannelPipeline. This only works if your Channel implementation
actually makes those calls to read()! Sadly, HTTP2StreamChannel did not:
we instead just recursed directly into the Channel's read0().
While I'm here I also noticed that we produced a lot of
channelReadComplete messages in the pipeline unnecessarily. We did this
in the service of having a read "fast-path" where new frames would be
automatically delivered into the ChannelPipeline without being buffered
until channelReadComplete. This fast-path is probably inadvisable: I
don't think it provided a meaningful performance benefit anyway,
especially as the removal of that fast-path allowed us to suppress
unnecessary calls to …
> Propagate read() through the pipeline.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/InboundWindowManager.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/InboundWindowManagerTests+XCTest.swift
- Tests/NIOHTTP2Tests/InboundWindowManagerTests.swift
Motivation:
In some cases it's possible for a stream to emit a WINDOW_UPDATE frame
after receiving close from the network. This is unfortunate because in
the eyes of the `NIOHTTP2Handler` the stream no longer exists which
results in a connection-level error.
Modifications:
- Add a flag to `deliverPendingReads` telling it whether it is allowed
to emit a WINDOW_UPDATE frame
- Use the above functionality when the stream is closing
Result:
WINDOW_UPDATE frames are no longer emitted from the stream as a result
of delivering pending reads while closing.
> Avoid emitting WINDOW_UPDATE frames when receiving stream closed

- Sources/NIOHPACK/IntegerCoding.swift
Motivation:
No point having conditional branches when the branch is always taken!
This doesn't hurt perf at all, the optimiser will trivially see through
this, but it does hurt readability. Relatedly, the single-letter
variable names here aren't great.
Modifications:
- Removed needless branch.
- Gave the variables better names.
Result:
Easier to understand code.
> Remove needless branch, clean up variable names.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
Motivation:
In an earlier patch (1e68e51) we attempted to avoid emitting
WINDOW_UPDATE frames on streams that were already closed on their
inbound side. This was largely a reasonable fix, but we missed an
important area: END_STREAM in a sequence of frames.
This would be triggered if we received multiple DATA frames in a row,
where the last one contained END_STREAM but an earlier one triggered a
WINDOW_UPDATE. The stream state machine would have seen the END_STREAM
already and will forbid the WINDOW_UPDATE, but the stream channel won't
yet have seen it and will try to send it.
The fix is easy enough: look for END_STREAM earlier.
Modifications:
- Check for END_STREAM when the stream channel receives the frame, not
when it passes it into the pipeline.
Result:
Fewer spurious connection …
> Move END_STREAM check earlier.

- Sources/NIOHTTP2/HTTP2UserEvents.swift
Motivation:
NIOHTTP2WindowUpdatedEvent was larger than 24 bytes, forcing heap
allocations whenever we wanted to put it into an existential. Given that
the range of the two optional integers stored on the type are both
explicitly documented to be the Int32 range, this type can happily just
contain Int32s.
Modifications:
- Changed the backing storage from Int? to Int32?.
Result:
NIOHTTP2WindowUpdatedEvent will be smaller.
Resolves #235.
> Shrink NIOHTTP2WindowUpdatedEvent.

- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_h1_request_response.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
Motivation:
The 2 to 1 codecs do a number of operations where they "peek" the
pseudo-headers. Each of these operations uses the HPACKHeaders
subscript, meaning that they allocate a temporary array for a field that
can, in a correct request/response, contain only one element. That's
very wasteful!
Modifications:
- Rewrite peekPseudoHeader to iterate instead, avoiding the array.
- Add allocaton counter test.
Result:
4 fewer allocations per HTTP request transformed on the server side,
2 fewer allocations per HTTP response transformed on the client side.
Resolves #244.
> Reduce allocations when peeking pseudo-headers.

- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_h1_request_response.swift
Motivation:
CI is spitting out a bunch of warnings about 'configureHTTP2Pipeline'
being deprecated; it is called without providing the inbound stream state
initializer. The non-deprecated version requires that this is
explicitly passed as `nil`.
Modifications:
- Explicitly set the 'inboundStreamInitializer' to `nil`
Result:
Fewer warnings.
> Use the non-deprecated 'configureHTTP2Pipeline' in benchmarks

- IntegrationTests/tests_01_allocation_counters/test_01_allocation_counts.sh
- IntegrationTests/tests_01_allocation_counters/test_01_resources/run-nio-http2-alloc-counter-tests.sh
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
- scripts/integration_tests.sh
Motivation:
I have suspicions that the allocation counter tests in NIOHTTP2 don't
fail properly, so let's bring the scaffolding up to date.
Modifications:
Update the few local files to the most recent NIO versions.
Result:
Smaller diffs to NIO, maybe better infrastructure?
> Update alloc counter scaffolding.

- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
Motivation:
- Typos are bugs. Bugs are bad.
Modifications:
- s/heder/header
Result:
Fewer typos
> Fix 'heder' typo

- .gitignore
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_1k_requests.swift
- Package.swift
- Sources/NIOHTTP2PerformanceTester/ServerOnly10KRequestsBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/main.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
Motivation:
Performance benchmarking wants accurate numbers, and a wide range of
possible benchmarks. One way to get somewhat more accurate numbers is to
use a tool like Cachegrind to measure the instruction counts of a
program. Cachegrind allows us to isolate a number of noise-introducing
effects, as "number of executed instructions" is a much more stable
number than how long a program takes to run.
When running under cachegrind we want to change the way our performance
benchmarks work. Instead of running lots of times to try to average out
noise, we only want to run once to save ourselves time, as the benchmark
itself should be drastically more stable.
While we're here, let's add some much more isolated benchmarks than our
current "make lots of streams" benchmark. This is basically the …
> Add benchmarks and improve benchmarking.

- Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
Motivation:
Heap allocations that aren't necessary for program correctness are to be
avoided.
Modifications:
- Avoid heap allocating for constructing indirect enum cases.
Result:
Fewer heap allocations.
Resolves #255.
Reduces instructions executed in cachegrind server-only benchmarks by
about 0.15%.
Reduces icache miss rate by 3% in cachegrind due to reduced jumps to
cold malloc code.
> Reduce allocations in OutboundFlowControlBuffer.

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/HTTP2StreamID.swift
- Tests/NIOHTTP2Tests/StreamIDTests+XCTest.swift
- Tests/NIOHTTP2Tests/StreamIDTests.swift
Motivation:
It's not possible (at least trivially) from the public API to determine
which peer in a connection initiated a given stream ID. In some cases
it's possible with prior knowledge (i.e. in a given application the
client may always initiate streams), however, such conditions aren't
guaranteed to always hold.
Modifications:
- Add `isClientInitiated` and `isServerInitiated` computed properties to
`HTTP2StreamID`.
- Add a few tests.
Result:
Users can easily get the answer to the question 'did a client/server
create this stream?'
> Add properties to HTTP2StreamID to determine stream initiator

- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_stream_teardown_100_concurrent.swift
- Sources/NIOHTTP2PerformanceTester/StreamTeardownBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/main.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
Motivation:
We don't have any benchmarks or alloc counter tests for doing stream
teardown with GOAWAY frames. While this isn't a terribly hot code path
and isn't terribly performance heavy with allocations, it's good to have
more data here.
Modifications:
- Write benchmarks and alloc counter tests that tear down many streams
with GOAWAY.
Result:
Better testing and alloc counter.
> Add benchmark and alloc test for GOAWAY teardown.

- Sources/NIOHTTP2PerformanceTester/Benchmark.swift
- Sources/NIOHTTP2PerformanceTester/HuffmanDecodingBenchmark.swift
- Sources/NIOHTTP2PerformanceTester/main.swift
Motivation:
The init() of all benchmarks will execute, even when we filter a
benchmark run down to a single benchmark. We should avoid doing heavy
work there, because it can confuse us when we look at traces elsewhere.
Modifications:
- Move some heavy work in the huffman benchmark base64 decode out of
init().
- Prevent setUp() and tearDown() from running if a test is filtered out.
- Avoid even creating benchmarks unless they're filtered in.
Result:
Less confusing benchmark traces.
> Move the huffman benchmark base64 out of init

- Sources/NIOHPACK/HuffmanCoding.swift
- docker/docker-compose.1804.53.yaml
Motivation:
A while ago we shimmed out the String unsafeUninitializedCapacity
initializer because while it was on the road to being implemented, it
hadn't actually been implemented. Now it has!
On Apple platforms, the initializer is guarded behind an availability
guard. We need to add that guard here. This means we need to keep hold
of the backport for a good long time, until we raise our minimum Apple
platform support to a new enough version. Happily, Linux on 5.3 should
just see a net win here.
Modifications:
- Updated to enable us to use the proper initializer.
Result:
Fewer allocations when screwing around with HPACK. Fractionally faster performance in general (~0.2%).
> Use proper String unsafeUninitializedCapacity initializer.

- Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
Motivation:
The outbound flow control buffer currently does a linear scan through
the pending data objects to work out how many bytes were buffered. Let's
burn an integer and just calculate these on the way in, making flushes
way cheaper.
Modifications:
- Update the number of bytes when we buffer the write, and make flushes
cheaper.
Result:
Moderate performance improvement in high throughput server benchmarks
(around 4%).
> Cheaper calculation of flushes.

- Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests+XCTest.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
- scripts/cachegrindify.sh
Motivation:
The OutboundFlowControlBuffer is responsible for managing DATA and
HEADERS frames for all streams in order to ensure that we obey HTTP/2
flow control rules, even when users don't. This object is therefore on
the data path for the vast majority of frames, and is extremely
performance sensitive.
Unfortunately, the current algorithm has some nasty performance cliffs.
Right now it has the awkward property of making flushes take an amount
of time linear in the number of streams on the connection, not the
number of streams that had had frames sent on them. The result is that
connections with highly parallel numbers of streams see extremely poor
performance when flushing, a problem that is exacerbated if other parts
of the HTTP/2 stack fail to coalesce those flushes.
We can clean …
> Reduce the cost of flushing

- Sources/NIOHPACK/HuffmanCoding.swift
Motivation:
Huffman decoding has rapidly become one of the most expensive parts of
the program. Some of the code here is unavoidably expensive, but there
is some unnecessary checked arithmetic here on offset. Removing that
provides a small but meaningful improvement to the performance of this
function.
Modifications:
- Remove the checked arithmetic on offset, which is bounded by a
previous operation that was already checked.
Result:
This function gets cheaper by about 4%, though the benchmark as a whole
only sees a 0.1% improvement.
> Micro-optimise checked arithmetic in huffman.

- Sources/NIOHPACK/HuffmanCoding.swift
Motivation:
In #263 we took advantage of the addition of the
unsafeUninitializedCapacity:initializingWith constructor on String,
added in the latest Swift SDKs and Swift versions.
Unfortunately, there were a few Xcode releases that shipped with Swift
5.3 but _without_ the macOS 11 SDK. These releases therefore had a 5.3
compiler, but no access to the macOS 11 SDK where the constructor is
defined.
This means this change regressed builds on those platforms.
Modifications:
Removed access to the fast-path initializer on Apple platforms in 5.3.
The initializer is present and will continue to work on non-Apple
platforms. Apple platforms will get access to that initializer from 5.4
onwards.
Result:
Fewer build issues for users using Xcode 12.0 and 12.1.
> Partially revert #263.

- Sources/NIOHPACK/HPACKHeader.swift
- Sources/NIOHPACK/HeaderTables.swift
Motivation:
When analysing remaining performance cliffs, we observed that
HeaderTableStorage.closestMatch was the source of a surprising amount of
ARC traffic. Further diagnosis revealed that we were ARCing string
storage as we iterated the table. Given that the table is constructed of
String/String pairs, the effect would be that if we scanned a table we
would emit two retains and two releases for each entry. Whenever we
encode a HTTP/2 header that we think could be indexed, we will scan the
static and possibly the dynamic tables to find a header that matches.
This ends up being a pretty nasty performance cost, as swift_retain and
swift_release are particularly complex on Strings, and often have
trouble with cache coherency and cache misses.
This got root-caused to …
> Reduce ARC in HPACK closestMatch

- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingDataState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingRstStreamState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingWindowUpdateState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingDataState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingPushPromiseState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingRstStreamState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingWindowUpdateState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/StateMachineResult.swift
- Sources/NIOHTTP2/HTTP2ConnectionStateChange.swift
Motivation:
To save myself some lines of code I wrote a function that was generic
over a protocol to copy out a pair of fields from a wide range of types.
It turns out this generic was triggering a retain/release on the state
machine states, which triggers 12 ARC operations total (6 retain/release
pairs).
Removing this generic and just, you know, calling a function with some
arguments turns out to save us a bunch of this ARC traffic.
Modifications:
- Remove the generic initializer of StateMachineResultWithEffect.
Result:
Approximately 1% performance improvement in hot benchmarks.
> Remove some generics that were triggering ARC

- Sources/NIOHPACK/HPACKHeader.swift
Motivation:
HPACKHeaders is a trivial data structure (a wrapper around Array) that
is present in the public API of all NIO HTTP/2 programs. This makes it a
tempting target for adding inlinable calls, primarily as a way to drive
down ARC. The fact that strings frequently travel across the API
boundary means that otherwise innocuous use-cases can trigger unexpected
ARC traffic.
Making as much of the implementation inlinable as possible reduces a lot
of this overhead and opens up the possibility for better performance in
a number of parts of the code, including in the core HTTP/2 protocol
engine, which operates extensively on this data type.
Modifications:
- Make basically everything inlinable.
Result:
Our benchmarks are about 0.7% faster.
> Make HPACKHeaders inlinable.

- Sources/NIOHTTP2PerformanceTester/main.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
The run-all mode of the performance tester inadvertently got removed in
a previous patch. This adds it back.
> Re-add "run all" mode to performance tester

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
Motivation:
The stream channel configure function uses a chain of futures where the
same can be achieved in fewer futures.
Modifications:
- Merge the future chains where possible in HTTP2StreamChannel.configure
Result:
A 1.3% reduction in instructions in server_only_10k_requests_1_concurrent
> Avoid unnecessary futures in stream creation

- Sources/NIOHTTP2/Frame Buffers/ConcurrentStreamBuffer.swift
- docker/docker-compose.yaml
- scripts/soundness.sh
To comply with the new [Swift code of conduct](https://swift.org/code-of-conduct/), let's make the language a little more welcoming.
- Replaced usages of "sanity" with "soundness"
- Added "sanity" to the list of unacceptable terms.
- Swift NIO HTTP2 is nicer.
> Use welcoming language

- Sources/NIOHPACK/HPACKHeader.swift
No-one calls this function so we can remove it.
> Delete dead code.

- Sources/NIOHTTP2PerformanceTester/Benchmark.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
- docker/docker-compose.2004.54.yaml
Motivation:
NIO 2.26.0 saved us some allocations, some of our limits are now too
high and CI fails as a result.
Modifications:
Adjust the allocation counter limits.
Result:
CI passes.
> Update allocation count requirements

- Package.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
Motivation:
SwiftNIO 2.27.0 added support for synchronous channel options allowing
callers to get options synchronously -- saving a future allocation -- if
they know they're on the correct event loop. 'HTTP2StreamChannel' should
support this.
Modifications:
- Add 'HTTP2StreamChannel.SynchronousOptions' with conformance to
'NIOSynchronousChannelOptions'
Result:
Callers can get and set options synchronously on 'HTTP2StreamChannel'
> Add sync option support to HTTP2StreamChannel

- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_1k_requests.swift
- Package.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
- docker/docker-compose.2004.54.yaml
Motivation:
SwiftNIO 2.27.0 added synchronous channel options. We can use these if
available when creating a stream channel to avoid a future allocation.
Modifications:
- 'getAutoReadFromParent' is synchronous when possible and now takes a
closure to handle the result.
- Update allocation counts (and sort them to make updating them easier,
this also includes switching the order we run test_1k_requests
interleaved and noninterleaved)
Result:
Fewer allocations.
> Use sync options when creating a stream channel

- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_request_response.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_create_client_stream_channel.swift
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
- docker/docker-compose.2004.54.yaml
Motivation:
Some of the allocation counting tests used frame-based stream channels
rather than the frame payload based ones. These were deprecated some
time ago.
Modifications:
- Update test handlers to be `HTTP2Frame.FramePayload` based
- Update the 'create_client_stream_channel' test to count streams rather
than summing their stream ID (as stream IDs aren't assigned until the
stream channel delivers pending writes for the first time).
- Update allocation limits
Result:
Allocation counting tests don't use deprecated APIs.
> Stop using deprecated API in allocation counting tests

- dev/alloc-limits-from-test-output
- dev/update-alloc-limits-to-last-completed-ci-build
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.2004.55.yaml
Motivation:
Our 5.5 allocation counts were off. Rather than just update that by hand
we should bring over some tooling to do it automatically.
Modifications:
- Bring over and adapt the update-alloc-limits scripts from NIO.
- Run them and commit the updates.
Result:
CI should pass again.
> Update our allocation counter numbers.

- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
Currently if a peer sends an empty `dataPayload` that signals the stream's end, the HTTP2ToHTTP1Codec will issue a HTTP1 `.body` with an empty `ByteBuffer` and an HTTP1 `.end`. The HTTP1 `.body` with the empty byte buffer can be saved.
The `BaseClientCodec` was changed in such a way, that an empty `dataPayload` that signals the stream's end, will only create a HTTP1 `.end`.
Fewer empty `byteBuffer`s.
> HTTP2ToHTTP1Codec: Fix receiving empty .body before .end

- Package.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
removeHandlers(channel:) was deprecated in NIO 2.32.0.
- Raise minimum required NIO version to 2.32.0
- Use removeHandlers(pipeline:)
We don't use deprecated API.
> Use non-deprecated API for removing handlers

- Sources/NIOHPACK/HPACKHeader.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
Motivation:
When getting the canonical form of header values any ascii whitespace
is stripped from the values. The current implementation does this by
doing equality checks on Character and dropping them from a Substring.
Modifications:
- Update the Substring._trimWhitespace() function to trim on a UTF8 view
- Add test
Result:
Retrieving the canonical form of header values is cheaper, significantly
so when values contain a lot of leading or trailing whitespace.
> Improve performance of `HPACKHeaders.subscript(canonicalForm:)`

- Sources/NIOHPACK/HPACKHeader.swift
Motivation:
The OWS rule from the HTTP semantics draft only considers 'SP' and
'HTAB' to be whitespace. We also (unnecessarily) consider CR and LF to
be whitespace.
Modifications:
- Remove CR and LF from the characters we consider to be whitespace
- Update tests
Result:
We no longer consider CR or LF to be whitespace when trimming
whitespace when producing the canonical form of header values.
> Don't count CR or LF as whitespace when trimming whitespace from header values

- Sources/NIOHPACK/HPACKHeader.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
Motivation:
The return value from `HPACKHeaders.subscript(canonicalForm:)` is
inconsistent with respect to returning empty strings.
If a value for a header field is an empty string then the canonical form
will not return that empty string. However, if a value is a string
containing only whitespace then an empty string will be returned.
Modifications:
- Filter out empty substrings after trimming whitespace
- Add a test
Result:
- `HPACKHeaders.subscript(canonicalForm:)` does not produce empty strings
> Ignore empty values when returning canonical form of header values

- Sources/NIOHPACK/HPACKHeader.swift
- Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
Motivation:
When getting the canonical form of headers we check whether the header
name is 'set-cookie' to avoid splitting values which are not safe to
split.
This check is done against a `lowercased()` version of the header name.
However, we don't need to produce a new `String` here as we already have
a case insensitive string comparision function.
Modifications:
- Add a test to verify that getting the canonical form of "set-cookie"
does not split any header values
- Switch to `isEqualCaseInsensitiveASCIIBytes`
Result:
More tests, cheaper comparision.
> Use case-insensitive comparision rather than lowercasing

- Sources/NIOHPACK/HPACKHeader.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
Currently we only remove forbidden HTTP/1.1 headers when translating to HTTP/2.0, if a connection header is present. Since a connection header is not required on HTTP/1.1, forward forbidden headers are currently sometimes forwarded (like "transfer-encoding").
- Remove forbidden HTTP/1.1 headers, even if no connection header is present.
We don't leak forbidden headers.
> Remove forbidden HTTP1 headers even if no connection header is present

- docker/docker-compose.2004.main.yaml
This patch updates the alloc counter to enforce the new numbers.
> Swift nightly has improved alloc counts.

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Motivation:
When we hit a stream error on an outbound frame, we don't currently
distinguish between them and channel errors. This makes it impossible
for anyone to tell them apart. It also makes it impossible for the
multiplexer to deliver these errors into the relevant stream channels
that triggered them, making it essentially certain they'll be lost.
Better diagnostics would be good, so we are providing them.
Modifications:
- Add new StreamError type that carries a stream ID and an underlying
error.
- Emit this StreamError type for outbound stream errors.
- Deliver this StreamError type into the relevant child channels when
possible.
Result:
Better diagnostics for stream errors.
> Deliver outbound stream errors to channels.

- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
When translating HTTP2 to HTTP1, developers assume HTTP1 header semantics. HTTP2 does not know the Transfer-Encoding header. For this reason, we should add the Transfer-Encoding header, when needed to HTTP2 requests and responses.
- Adds the Transfer-Encoding to incoming HTTP requests on the server http2 to http1 translation side
- Adds the Transfer-Encoding to incoming HTTP responses on the client http2 to http1 translation side
Users get more real http1.1 semantics, when using the HTTP2 to HTTP1 translation.
> Add Transfer-Encoding chunked to HTTP1 requests and responses.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
In the AsyncHTTPClient the read event is not always forwarded right away. We have seen instances, in which we see a `HTTPClientError.remoteConnectionClosed` error, on requests that finish normally. https://github.com/swift-server/async-http-client/issues/488 
On deeper inspection, I noticed: If there is no unsatisfied read event, when a stream is closed, the pending reads are not forwarded. This can lead to response bytes being ignored on successful requests. NIOHTTP2 should behave as NIO and force forward all pending reads on channelInactive.
- Forward all pending reads on channelInactive even if no read event has hit the channel
All requests will receive the complete request body.
> Forward all reads before stream channel inactive

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Tests/NIOHTTP2Tests/ReentrancyTests+XCTest.swift
- Tests/NIOHTTP2Tests/ReentrancyTests.swift
In rare cases, the `HTTP2ChannelHandler`s method `unbufferAndFlushAutomaticFrames` and the `HTTP2StreaMultiplexer`s `newConnectionWindowSize` method were recursively calling themselves. This was causing a stack overflow. To protect ourselves from this stack overflow, I added a variable to guard against reentrancy inside the `unbufferAndFlushAutomaticFrames` method.
> Protect against reentrancy inside the HTT2ChannelHandler

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Motivation:
The `wroteFrame` flag in `HTTP2ChannelHandler` indicates whether a frame
has been written. This flag is checked before flushing in order to avoid
unnecessary flushes. Unfortunately this is only ever set to `true`.
Modifications:
- Add a `flushIfNecessary` to check and toggle `wroteFrame` and flush if
necessary
- Add a test
Result:
- Few unnecessary flushes
- Resolves https://github.com/apple/swift-nio-http2/issues/245
> Only flush when necessary in the HTTP2ChannelHandler

- docker/docker-compose.2004.main.yaml
Motivation:
Recent nightly builds have introduced small allocation regressions.
Modifications:
Update allocation limits for nightly Swift builds.
Result:
CI passes.
> Update nightly allocation limits

- Sources/NIOHPACK/HPACKErrors.swift
Motivation:
A new 'UnrepresentableInteger' error was added in GHSA-w3f6-pc54-gfw7.
This was added as internal so that the advisory could be published as a
patch release rather than a minor.
This error should be public so that callers may hold an instance of it.
Modifications:
- Make UnrepresentableInteger public
Result:
UnrepresentableInteger is part of the public API.
> Make UnrepresentableInteger public

- Sources/NIOHPACK/IntegerCoding.swift
Motivation
Checked math is great when you aren't sure what the constraints are, but
in some places we happen to know that all the arithmetic operations
occur in a defined domain and range. In those cases, we can improve the
codegen by adopting unchecked math.
Modifications
Widely adopt unchecked math in encodeInteger.
Result
Better codegen for encodeInteger.
> Use unchecked math in encodeInteger

- Sources/NIOHTTP2/HTTP2FrameParser.swift
- docker/docker-compose.1604.52.yaml
- docker/docker-compose.1804.53.yaml
- docker/docker-compose.2004.54.yaml
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2004.main.yaml
- scripts/soundness.sh
Some soundness checks were broken by our security fix (thanks to @tomerd in #330) and the allocation counts got dropped by the rewrite. This fixes both.
> Update alloc limits and clean up soundness

- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingPushPromiseState.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
Nowhere in the PUSH_PROMISE code do we explicitly check whether or not
we're a client or a server, and we don't provide special handling for
SETTINGS_ENABLE_PUSH contingent on that fact. As a result, we do
technically allow clients to push. This eventually gets caught, but not
until we've created an idle stream, which we shouldn't do.
Modifications:
- Forbid clients from pushing.
Result:
Clients won't be allowed to push.
> Clients can't push!

- Sources/NIOHPACK/HPACKHeader.swift
- Tests/NIOHPACKTests/HPACKHeadersTests+XCTest.swift
- Tests/NIOHPACKTests/HPACKHeadersTests.swift
Motivation:
Header normalisation is expensive when the input headers contain a large
number of connection header values.
Modifications:
- When the headers to normalise contain more than 32 connection header
values use a set to provide constant time lookup, rather than linear.
Result:
Better perf for HTTPHeader normalisation with large connection header
value lists.
> Improve HTTPHeader normalisation performance for large inputs

- Package.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
`NIOAtomics` was deprecated in https://github.com/apple/swift-nio/pull/2204 in favor of `swift-atomics` https://github.com/apple/swift-atomics
> Use `swift-atomics` instead of `NIOAtomics`

- Package@swift-5.4.swift
- Package@swift-5.5.swift
- Sources/NIOHTTP2/Docs.docc/index.md
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2ErrorCode.swift
- Sources/NIOHTTP2/HTTP2Frame.swift
- Sources/NIOHTTP2/HTTP2PingData.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/HTTP2Settings.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamID.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Sources/NIOHTTP2/HTTP2UserEvents.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- docker/docker-compose.1804.54.yaml
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2004.57.yaml
- docker/docker-compose.2004.main.yaml
- docker/docker-compose.yaml
- scripts/soundness.sh
Motivation
Documentation is nice, and we can help support users by providing useful
clear docs.
Modifications
Add Docc to 5.6 and later builds
Make sure symbol references work
Add overview docs
Result
Nice rendering docs
> Use Docc for documentation

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingHeadersState.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
Improve error messages
Modifications:
Replaced no such stream error with correct createdStreamAfterGoaway error
> Better GoAWAY error

- docker/docker-compose.1804.54.yaml
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2004.57.yaml
- docker/docker-compose.2004.main.yaml
Motivation:
NIO 2.42.0 was just released and some alloc tests have regressed. These
come from EmbeddedChannelCore adding atomics.
Modifications:
- Update alloc limits
Result:
CI passes
> Update allocation limits

- README.md
- Sources/NIOHPACK/HPACKEncoder.swift
- Sources/NIOHPACK/HeaderTables.swift
- Sources/NIOHPACK/IndexedHeaderTable.swift
- Sources/NIOHTTP2/HTTP2Frame.swift
We only support Swift 5.5.2+. 
Remove all `#if swift(>=5.5)` conditional compilation blocks.
less branching
> Remove `#if compiler(>=5.5)`

- Sources/NIOHPACK/DynamicHeaderTable.swift
- Sources/NIOHPACK/HPACKDecoder.swift
- Sources/NIOHPACK/HPACKEncoder.swift
- Sources/NIOHPACK/HPACKHeader.swift
- Sources/NIOHPACK/HeaderTables.swift
- Sources/NIOHTTP2/HTTP2ErrorCode.swift
- Sources/NIOHTTP2/HTTP2Frame.swift
- Sources/NIOHTTP2/HTTP2PingData.swift
- Sources/NIOHTTP2/HTTP2Settings.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamID.swift
- Sources/NIOHTTP2/HTTP2UserEvents.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
Motivation:
NIOSendable was deprecated in https://github.com/apple/swift-nio/pull/2291 as the earliest supported Swift version in NIO land is now 5.5.
Modifications:
- s/NIOSendable/Sendable
Result:
Avoids deprecation warnings when the above patch is released.
> Replace NIOSendable with Sendable

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2PerformanceTester/HuffmanDecodingBenchmark.swift
- Tests/NIOHPACKTests/HPACKIntegrationTests.swift
- Tests/NIOHPACKTests/HeaderTableTests.swift
- Tests/NIOHPACKTests/HuffmanCodingTests.swift
- Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
- Tests/NIOHTTP2Tests/ConcurrentStreamBufferTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
- Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
- Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
#fileID introduced in Swift 5.3, so no longer need to use #file anywhere                                  
Modifications:
Changed #file to #filePath or #fileID depending on situation
> Use #fileID/#filePath instead of #file

- Sources/NIOHTTP2/ContentLengthVerifier.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Tests/NIOHTTP2Tests/ContentLengthVerifierTests+XCTest.swift
- Tests/NIOHTTP2Tests/ContentLengthVerifierTests.swift
`ContentLengthVerifier` `init` throws on negative values
We discovered that this code path can result in an arithmetic overflow in the case where the content-length header has `INT_MIN` value. Since negative content-lengths don't have any meaning anyway we may as well throw if we encounter one so the decoding can be aborted.
* ContentLengthVerifier init throws a `ContentLengthHeaderNegative` error when the decoded value is < 0.
* ContentLengthVerifier init throws a `ContentLengthHeaderMalformedValue` error when the value cannot be decoded, e.g. it is out of bounds for Int or is an invalid string.
We will no longer panic for `INT_MIN` content-lengths and will fail decoding if one of various invalid values is encountered.
> Content length verifier negative check

- Sources/NIOHTTP2/HTTP2Frame.swift
Motivation:
Using indirect cases makes unwrapping and rewrapping HTTP/2 frames more expensive than it needs to be. As FramePayload.Data is essentially always stuffed into a FramePayload enum, we may as well just class-back it and avoid the extra allocs.
Modifications:
Make FramePayload.Data class-backed
Result:
Fewer allocations in many use-cases
> Make FramePayload.Data class-backed

- README.md
Motivation:
The NIO docs are now published on the Swift Package Index but the README still refers to GitHub pages.
Modifications:
- Update README and other docs to point to Swift Package Index.
Result:
Documentation links work
> Point docs to Swift Package Index

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingPushPromiseState.swift
- Sources/NIOHTTP2/ContentLengthVerifier.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Sources/NIOHTTP2Server/main.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/ContentLengthVerifierTests+XCTest.swift
- Tests/NIOHTTP2Tests/ContentLengthVerifierTests.swift
Motivation:
Currently, swift-nio-http2 ignores content length when handling a response to a HEAD request and handling a 304 response.
Modifications:
Changing ContentLengthVerifier and any functions called
> ContentLengthVerifier Update

- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
When we added new content length verification and new errors, we didn't update the places that were handling the old error. This code updates that logic to ensure that we don't crash.
Modifications:
Add new internal protocol to which the content length validation errors conform.
Catch that protocol instead.
Result:
No crashes on invalid content-length
> Content-Length errors shouldn't crash

- Sources/NIOHTTP2/WatermarkedFlowController.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Motivation:
The stream channel updates its writability manager when issuing a write to the parent channel and when the write promise has been succeeded. If the write promise has already been succeeded then the writability manager can be updated in the wrong order which can lead to underflow.
Modifications:
- Use signed arithmetic in the writability manager and allow pending
bytes to become (briefly) negative.
Result:
The writability manager's pending bytes shouldn't underflow.
> Better handle writes issued with already completed promises

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/ReentrancyTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
channelActive must always precede channelInactive. Unfortunately, this isn't guaranteed right now: if we happen to get channelInactive as a result of our writing the preamble we'll fire them in the wrong order. Many systems can tolerate this, but we should avoid doing this anyway.
Modifications:
- Added a state enum to keep track of the state we're in
- Use that state enum to ensure we deliver active/inactive in the right order
- Additionally police other unexpected active/inactive behaviours
Result:
We'll appropriately police the state.
> Ensure that we fire channelActive and channelInactive in order

- Sources/NIOHPACK/HPACKEncoder.swift
- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasLocalSettings.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
- Tests/NIOHPACKTests/HPACKCodingTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
When remote peers set the value of HEADER_TABLE_SIZE to any non-default value, or when we update it, we should respect that value when we're emitting headers.
Unfortunately, right now we don't. In particular, we manage to update the wrong setting: when the peer sets HEADER_TABLE_SIZE we bound the maximum size of the dynamic table _they_ can use, not the maximum size _we_ can use. That's incorrect by the spec, which says:
> This setting allows the sender to inform the remote endpoint of the
> maximum size of the compression table used to decode field blocks,
> in units of octets. The encoder can select any size equal to or less
> than this value by using signaling specific to the compression
> format inside a field block (see [COMPRESSION]).
If a peer sent us …
> Correctly respect changes to HEADER_TABLE_SIZE

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
When we started checking active/inactive ordering, we added code that rejected some channel pipeline state transitions. That code was too strict: it is absolutely possible to see channelInactive before channelActive in well-functioning programs.
We'll still call this an error, but we don't need to crash in debug mode when we see it.
Modifications:
- Made channelInactive before channelActive tolerated.
Result:
More reliable code
Resolves #375
> Soften errors when seeing inactive before active

- scripts/soundness.sh
Motivation:
Soundness check currently fails for copyright statements including 2023 as the year
Modifications:
add '3' to the checking regex
Result:
Soundness checks should not fail for documents created this year
> make soundness check aware of 2023

- Sources/NIOHTTP2/HTTP2ChannelHandler+ConnectionDemultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2UserEvents.swift
- Sources/NIOHTTP2/InboundEventBuffer.swift
Motivation:
This change prepares for future work to embed the connection demultiplexer within the `HTTP2ChannelHandler` which will improve performance by removing the need for passing expensive `InboundUserEvent`s.
Modifications:
This first step defines a new protocol (`NIOHTTP2ConnectionDemultiplexer`) which will later be used to abstract over the embedded and legacy separate demultiplexer code but at the moment should not change the logic.
Result:
Behaviour should be unchanged.
> Add no-op NIOHTTP2ConnectionDemultiplexer

- Sources/NIOHTTP2/HTTP2ChannelHandler+InboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2StreamChannel+OutboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2StreamChannel+StreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
This change prepares for future work to embed the connection multiplexer within the `HTTP2ChannelHandler` which will improve performance by removing the need for passing expensive `InboundUserEvent`s.
* Define a new protocol (`OutboundStreamMultiplexer `; named such to avoid confusion with the legacy handler, `HTTP2StreamMultiplexer`) which will later be used to abstract over the inline and legacy multiplexer code but at the moment should not change the logic.
* Rename `NIOHTTP2ConnectionDemultiplexer` -> `InboundStreamMultiplexer`
Behaviour should be unchanged.
> Add multiplexer protocol abstraction in http2 stream channel

- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2StreamDelegate.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
- Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests+XCTest.swift
- Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests.swift
Motivation:
Allow handlers in the pipeline to be notified when an HTTP2 stream is created or closed.
Modifications:
Store an instance of a `NIOHTTP2StreamDelegate` on the `NIOHTTP2Handler` and `InlineStreamMultiplexer` so that it may be called when streams are created or closed.
Added tests.
Result:
`NIOHTTP2Handler`s init'd with a `streamDelegate` will now call into that delegate's `streamCreated` and `streamClosed` functions.
> Expose a functional `NIOHTTP2StreamDelegate`

- Sources/NIOHTTP2/HTTP2StreamDelegate.swift
- Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests.swift
Motivation:
Remove `NIOHTTP2StreamDelegate` `Sendable` conformance requirement. This wasn't needed in the first place because `NIOHTTP2Handler` is not `Sendable`, therefore it never leaves the thread on which it is created.
The delegate may still be `Sendable` depending on the implementation but it is not a strict requirement.
Modifications:
Remove `NIOHTTP2StreamDelegate` `Sendable` requirement
Result:
Sendable is no longer required for `NIOHTTP2StreamDelegate` conformance
> Remove NIOHTTP2StreamDelegate Sendable requirement

- IntegrationTests/tests_01_allocation_counters/test_01_resources/run-nio-http2-alloc-counter-tests.sh
- IntegrationTests/tests_01_allocation_counters/test_01_resources/shared.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_1k_requests.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_h1_request_response.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_request_response.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_create_client_stream_channel.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_stream_teardown_100_concurrent.swift
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.main.yaml
Allocation tests for direct stream multiplexing
Increase allocation test coverage to encompass new HTTP2Handler direct stream multiplexing.
- Duplicate existing relevant allocation tests
- Introduce a new test for inline and legacy modes which creates multiple streams and then performs many requests on each. This is to give an indication of the performance change through many requests and window update frames.
More allocation test coverage.
> Allocation tests for direct stream multiplexing

- Sources/NIOHTTP2/Frame Buffers/OutboundFrameBuffer.swift
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.main.yaml
Motivation:
CiruclarBuffer always allocates on init as it never has a zero capacity. It is implemented in such a way that changing this is not trivial. The compound outbound buffer creates a marked circular buffer unconditionally on each call but only uses it if there are streams to drop.
Modifications:
Add a static empty marked circular buffer to the compound outbound buffer and rely on CoW semantics to avoid the allocation for each call in cases where there are no frames to drop.
Result:
Fewer allocations.
> Avoid allocation in outbound frame buffer

- Sources/NIOHTTP2/HTTP2Frame.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
`estimatedFrameSize` aims to estimate the number of bytes a frame will use on the wire. It includes the 9-octed frame header and is currently used for flow control estimates but according to spec it shouldn't include those 9 bytes https://www.rfc-editor.org/rfc/rfc9113.html#section-6.9.1
Modifications:
Replace `estimatedFrameSize` with `flowControlledSize` which ignores the 9-octed frame header and update tests.
Result:
Flow control calculations should be more accurate
> Replace estimatedFrameSize with flowControlledSize

- Sources/NIOHTTP2/HTTP2Frame.swift
Motivation:
HTTP2 flow control only cares about DATA frame sizes so we can be more accurate and drop the complexity of `flowControlledSize`
Modifications:
`flowControlledSize only returns non-zero sizes for `DATA` frames
Result:
`flowControlledSize only returns non-zero sizes for `DATA` frames
> flowControlledSize only counts DATA frames

- Sources/NIOHTTP2/HTTP2ChannelHandler+InboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.main.yaml
Motivation:
The `HTTP2StreamChannel` keeps track of how many bytes have been written and how many are buffered for use in evaluating the 'writability' of the stream channel. Bytes are considered 'written' or at least no longer buffered when the write is completed (successfully or errored). In order to make the determination of when writes are complete across channel handlers we attach a promise to all writes and deduct adjust the byte counts on completion. Creating and attaching these promises requires costly allocations.
Modifications:
We can remove the need to create these promises for the new inline stream multiplexer because the multiplexer and man HTTP2 channel operations are now all within the `HTTP2ChannelHandler`. This change calls the `writabilityManager` directly when writes are …
> Inline multiplexer calls writability mgr directly

- Sources/NIOHPACK/HPACKHeader.swift
- Tests/NIOHPACKTests/HPACKHeadersTests.swift
- scripts/soundness.sh
In scenarios, in which we want to send lots of small HTTP/2 requests, we want to reuse a single HPACKHeaders object as often as we can. To support this we should have a `removeAll(keepingCapacity:)` method.
> Add `HPACKHeader.removeAll(keepingCapacity:)`

- dev/update-alloc-limits-to-last-completed-ci-build
Motivation:
update alloc counts ci build script to reflect our current CI pipelines
Modifications:
update alloc counts ci build script to add 5.9 and drop 5.5 to reflect our CI pipelines
Result:
Script should update counts successfully
> update alloc counts ci build script for 5.9

- Sources/NIOHPACK/HuffmanCoding.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
This will enable compiling the package to `xrOS` using the right code.
> Replace os() with canImport(Darwin)

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineInlineMultiplexerTests.swift
There are a few places where bugs / poorly structured code crept in during the inline multiplexer work. This attempts to address some of them:
* overly long lines
* mis-named variables
* unnecessary use of generics in one case
> Inline http2 fixups

- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
Motivation:
This continues the work to expose functionality which allows users to interact with HTTP/2 connections via async abstractions and using structured concurrency.
We build atop of previous work to configure pipelines to deal with HTTP/2 (with no protocol negotiation) and to wrap connection/stream channels with `NIOAsyncChannel`s. This will allow users to iterate over streams and HTTP2Frames.
Modifications:
Provide functions which configure channels and pipelines with the HTTP2 handler, expose a multiplexer for dealing with streams and wrap connection and stream channels with `NIOAsyncChannel`s.
Result:
Users will be able to create and interact with HTTP/2 connections via `NIOAsyncChannel`s. Because HTTP/2 is a negotiated protocol and we do not yet handle it, this is of limited …
> HTTP/2 pipeline NIOAsyncChannel pipeline config

- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
Motivation:
Marking `NIOHTTP2InboundStreamChannels.AsyncIterator` as non-sendable fails to compile on 5.6 however implicitly non-sendable will do, this is a nice-to-have.
Modifications:
Move the non-sendable annotation to only apply >= 5.7
Result:
`NIOHTTP2InboundStreamChannels.AsyncIterator` is implicitly non-sendable on 5.6
> H2 stream AsyncIterator non-sendable on 5.7

- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
Motivation:
Recent additions to pipeline configuration did not expose some of the `NIOAsyncChannel` configuration.
Modifications:
Expose `backpressureStrategy`, `isOutboundHalfClosureEnabled`.
I think specific naming and object encapsulation for these parameters should be discussed later before SPI is removed and we review the API as a whole.
Result:
Pipelie helpers for `NIOAsyncChannel` expose `backpressureStrategy`, `isOutboundHalfClosureEnabled`.
> Add additional NIOAsyncChannel config

- Sources/NIOHPACK/HPACKHeader.swift
- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HTTP2SettingsState.swift
- Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2ErrorCode.swift
- Sources/NIOHTTP2/HTTP2FlowControlWindow.swift
- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
- Sources/NIOHTTP2/StreamMap.swift
Motivation:
Tweaking the formatting of the DocC comments enables syntax highlighting for parameter names in Xcode
Modifications:
Whitespace changes, capitalisation changes and added a parameter description for `indexing` in HOACKHeaders `replaceOrAdd`, `add`.
Result:
More readable DocC comments
> Tweak formatting of function DocC comments

- Package.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
In my latest PR in NIO, I removed a bunch of API from the bootstrap methods to make the API easier to digest and reduce a number of duplicated code issues.
This PR adopts the latest NIO changes and adapts the APIs in H2. More specifically, it removes the `NIOAsyncChannel` convenience methods and makes sure that everything aligns nicely with the proposes bootstrap APIs.
We now have the APIs in place to bootstrap a protocol negotiated H1/H2 server.
> Adopt latest AsyncChannel changes

- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Motivation:
Make sure the order of `HTTP2Frame`s that are fired through the pipeline of a `HTTP2StreamChannel` by `HTTP2CommonInboundStreamMultiplexer` is correct when a `read()` call on the parent channel synchronously causes further frames to be processed.
Modifications:
Reorder calls in `HTTP2CommonInboundStreamMultiplexer.receivedFrame(frame:context:multiplexer)` so that initial header frame is buffered and processed first.
Result:
Resolves #410 and makes newly added test case `HTTP2StreamMultiplexerTests.testMultiplexerFiresInitialFramesInCorrectOrder()` pass.
> Fix parent channel `read()` call on `HTTP2StreamChannel` initialization causing incorrect order of inbound `HTTP2Frame`s

- Package.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
A recent PR to https://github.com/apple/swift-nio/pull/2497 adjusted the SPI for protocol negotiation.
- Bump minimum NIO version to 2.58.0
- Update use of `NIOTypedApplicationProtocolNegotiationHandler`.
Compiles again with latest NIO.
> Update to latest NIO with updated protocol negotiation SPI

- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
- Sources/NIOHTTP2PerformanceTester/Bench1Conn10kRequests.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
When adding in the SPI methods for exposing async sequences of HTTP/2 streams we moved the stream initialization to a subtly different location so that it was easier to exfiltrate the outputs of those initialization functions (such as protocol negotiation outputs).
In some cases this broke ordering expectations.
Yield the (optionally wrapped) channels as initializer outputs to the async stream when the initialization and activation steps succeed.
Changes only exist within SPI. Async inbound stream channel initialization now matches previous behavior.
> Async stream initializers order matches existing

- Sources/NIOHTTP2/DOSHeuristics.swift
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
Motivation:
The type inference system isn't able to work out the default clock type in the DOSHeuristics init on Swift 5.6 so this change makes it more explicit
Modifications:
Add more explicit inits
Result:
The code should build on 5.6 and later
> DOSHeuristics DeadlineClock more explicit on 5.6

- Package.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
We previously developed an async API for NIO HTTP/2 which was guarded under SPI. Now that the swift-nio async API is released we can reintroduce this code promoted to SPI.
This change introduces:
* `AsyncStreamMultiplexer` - an async variant of the HTTP/2 stream multiplexer which can be used to create outbound streams and provide access to an async sequence (`NIOHTTP2AsyncSequence`) of inbound streams
* New pipeline configuration functions (e.g. `configureAsyncHTTP2Pipeline`) to support the new async mode
> HTTP/2 Async API

- Tests/NIOHPACKTests/HPACKIntegrationTests.swift
We had a retroactive `CustomDebugStringConvertible` conformance to `ByteBufferView` in one of our tests harnesses which caused compiler errors in the latest nightlies.
This PR removes the retroactive conformance.
No more compiler errors.
> Remove retroactive `CustomDebugStringConvertible` conformance in tests

- Sources/NIOHTTP2/HTTP2ChannelHandler+InboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/HTTP2StreamChannel+OutboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
Mark public generic async methods inlinable
Mark generic async methods inlinable where possible to improve performance.
Multiple methods marked `@inlinable`
Performance increase
> Mark public generic async methods inlinable

- Sources/NIOHPACK/HPACKEncoder.swift
- Sources/NIOHPACK/IntegerCoding.swift
- Tests/NIOHPACKTests/IntegerCodingTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
This project doesn't currently build for watchOS because some tests make use of 64-bit integer literals.
```
IntegerCodingTests.swift:161:115: Integer literal '9151314442816848127' overflows when stored into 'Int'
```
Beyond the test code, the integer encoding logic makes use of `UInt`, which will be `UInt64` on some platforms and `UInt32` on others, e.g. some Apple Watch versions.
- Compile out the tests that use 64-bit integer literals with `#if !os(watchOS)`.
- Use explicit `UInt64` instead of `UInt` for encoding methods.
Code can now build for watchOS.
> Use explicit 64-bit UInt64 to support 32-bit platforms

- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
If a task iterating over inbound streams using the new async API is cancelled then it can lead to the process crashing as we hit a precondition which guards against yielding to a terminated NIOHTTP2AsyncSequence.
Remove the precondition.
The code no longer crashes, instead it silently drops the yielded value.
Doing more than this such as closing the connection requires rethinking more of the API.
> Remove precondition: yielding to terminated AsyncSequence

- Sources/NIOHTTP2PerformanceTester/Bench1Conn10kRequests.swift
`Bench1Conn10kRequests` performance tester incorrectly used a `NIOLoopBound` to access the `HTTP2StreamMultiplexer` to create streams.
Access the multiplexer by safely obtaining a reference to the handler.
- `Bench1Conn10kRequests` are not broken
> fix Bench1Conn10kRequests crash

- Sources/NIOHTTP2/HTTP2FrameParser.swift
Motivation:
CoWs appear when switching over the current state of the parser and holding it while also modifying it - inside `processNExtState()`. Following `append(bytes: ByteBuffer)`'s pattern, we should use a function that sets the state to an intermediary one with no associated data, before making the transformations.
Modifications:
- updated the `avoidParserCoW()` helper function to take into consideration throwing functions
- used it in the switch cases over the parser state inside `processNextState()` 
Result:
CoW will be avoided when changing the state of the HTTP2FrameDecoder while decoding, so we won't have unnecessary heap allocations.
> Avoid CoW while processing the next state when HTTP2FrameDecoder decodes

- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
We should check the compiler and not the language version. Technically it should be the SDK but `Async*Stream` ship in the standard library so this is fine. Checking the language version is definitely not correct.
https://github.com/apple/swift-nio/issues/2718
> test compiler not language version

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
Motivation:
`configureAsyncHTTP2Pipeline` doesn't allow a stream delegate to be specified. As the async pipeline uses the "inline" stream multiplexer there's no way to account for streams within the connection channel.
Modifications:
- Add a sync and async variants of `configureAsyncHTTP2Pipeline` which accepts an optional stream delegate
- Rewrite the existing helpers in terms of the new one
Result:
Users can configure an async http pipeline with a stream delegate.
> Add a variant of configureAsyncHTTP2Pipeline which takes a stream delegate

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HTTP2SettingsState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasExtendedConnectSettings.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasLocalSettings.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
- Sources/NIOHTTP2/HPACKHeaders+Validation.swift
- Sources/NIOHTTP2/HTTP2ConnectionStateChange.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/StreamStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/HTTP2ErrorTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
> Implement RFC8441 Extended CONNECT

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2/HTTP2FrameParser.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
- Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
- Tests/NIOHTTP2Tests/TestUtilities.swift
Motivation:
Long sequences of CONTINUATION frames can be used to mount attacks by attempting to get a remote peer to consume large amounts of memory.
Modifications:
- Add a limit to the number of sequential CONTINUATION frames that can be received. This limit is configurable by users at the NIOHTTP2Handler level and has a default value of 5. When this limit is exceeded, the recipient responds with a GOAWAY frame and an "Enhance Your Calm" error of a newly created type `ExcessiveContinuationFrames`.
Result:
Long sequences of CONTINUATION frames are now rejected by the recipient.
> Reject long sequences of CONTINUATION frames

- Sources/NIOHTTP2/Error+Any.swift
- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- docker/docker-compose.2204.510.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
Motivation:
Existential errors are unconditionally boxed. We typically create and use errors to fail promises when performing cleanup work. One example of this is failing pending writes when a stream channel is closed, however this is done unconditionally which means every stream channel incurs an allocation when it closes.
Modifications:
- Statically create some existential errors ahead of time
Result:
Fewer allocations
> Reduce error allocations

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- docker/docker-compose.2204.510.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
Motivation:
When the stream channel has closed it drops all of its pending reads. It does this by calling 'removeAll()' on its CircularBuffer. The buffers underlying storage is emptied and then a `nil` is appended (internally CircularBuffer is never empty) which triggers an allocation.
Modifications:
- Remove all but keep capacity
Result:
Fewer allocations
> Keep capacity when dropping pending reads in the stream channel

- Tests/NIOHTTP2Tests/TestUtilities.swift
Swift 6 has switched to this new Android overlay, swiftlang/swift#74758, which I've been testing on this repo without a problem using my daily Android CI for weeks now, finagolfin/swift-android-sdk#151.
> Use Bionic module from new Android overlay in Swift 6 instead

- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- docker/docker-compose.2204.510.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
When creating stream channels on the `InlineStreamMultiplexer`, we are currently performing a `flatSubmit` on two different codepaths. This allocates two ELFs: one on `submit`, and one on `flatMap`. This is unnecessary, as we could do with just one allocation.
Create a single ELP and call `execute` on the EL instead of using `flatSubmit`.
Fewer allocations
> Reduce allocations on `InlineStreamMultiplexer/createStreamChannel`

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- docker/docker-compose.2204.510.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
Motivation:
The HTTP2StreamChannel stores two atomic booleans for whether the channel is active and writable. These are only accessed externally and access is relatively infrequent. Each atomic requires an allocation, instead we can just protect each with a single lock.
Modifications:
- Combine the two atomics into a single 'flags' struct protected by a locked value box
Result:
Fewer alloations
> Reduce allocs in HTTP2StreamChannel

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
- Sources/NIOHTTP2/ConnectionStateMachine/LocallyQuiescingState.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Currently, HEADERS frames are ignored by the client on a client-initiated stream after the client sends a GOAWAY.
As per [Section 6.8 (GOAWAY) in RFC 9113](https://httpwg.org/specs/rfc9113#GOAWAY):
_"Once the GOAWAY is sent, the sender will ignore frames sent on streams **initiated by the receiver** if the stream has an identifier higher than the included last stream identifier."_
In this case, the client (sender) should **not** ignore the HEADERS frame as the stream is initiated by the _client_, not the receiver.
Fixed the condition in the `receiveHeaders` function (given `LocallyQuiescingState`) in `ReceivingHeadersState.swift` to work for _both_ the client and server roles -- before this change, the condition is only correct when `self.role == ConnectionRole.server`.
HEADERS frames are …
> Fix bug where client ignores HEADERS frames on open stream when locally quiescing

- .github/release.yml
We want to start using the GH based release notes drafting to make it easier for publishing new releases.
This PR adds the `release.yml` and configured the correct labels
> Adopt `release.yml`

- Package.swift
Motivation:
Building swift-nio-http2 with Swift 5.8 fails due to a compiler error when building swift-docc-plugin (https://github.com/swiftlang/swift-docc-plugin/issues/94).
Modifications:
- Adjust the dependency version of swift-docc-plugin from `from: "1.0.0"` to `"1.0.0"..<"1.4.0"`.
Result:
Building swift-nio-http2 with Swift 5.8 will now be successful.
> Upper-bound swift-docc-plugin dependency version

- Package.swift
Updates the swift-docc-plugin dependency to remove the upper bound (fixed by https://github.com/swiftlang/swift-docc-plugin/pull/96).
~~This PR is in a draft state so that we can verify that https://github.com/swiftlang/swift-docc-plugin/pull/96 resolves this issue in this project before merging and creating a tag.~~
We've created the tag and I updated the PR.
> Remove upper bound for swift-docc-plugin version

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerInlineStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Motivation:
When the connection is fully quiesced, an endpoint responds with a connection error when it receives or tries to respond to a PING frame. This behaviour is unnecessary.
Modifications:
- Adjust `HTTP2ConnectionStateMachine` to successfully receive and send PING frames even when the connection is fully quiesced.
Result:
When the connection is fully quiesced, an endpoint will treat receipt and sending of a PING frame as it would when the connection is active.
> Accept PING frames even when fully quiesced

- Sources/NIOHTTP2/HTTP2ChannelHandler+InboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
- Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerInlineStreamMultiplexerTests.swift
Motivation:
NIO has a 'ChannelShouldQuiesceEvent' which channels can listen for in order to know when they should quiesce. This is typically used to initiate a graceful shutdown of an HTTP/2 server. However, child channels aren't notified of this event so HTTP/2 servers must keep track of streams separately in order to notify them when the server is quiescing.
Modifications:
- Propagate the `ChannelShouldQuiesceEvent` to child channels
Result:
Child channels can watch for `ChannelShouldQuiesceEvent`s
> Propagate ChannelShouldQuiesceEvent to child channels

- Sources/NIOHTTP2/Docs.docc/Articles/Multiplexing-for-maintainers.md
Motivation:
It's hard to keep track of all the pieces that do multiplexing. When making some changes I found myself writing down what each piece did and how they fit together. I think this is generally useful information for anyone maintaining the library.
Modifications:
- Add a DocC article about the different multiplexing approaches that's aimed at _maintainers_ of NIOHTTP2.
Result:
Easier to learn about how multiplexing is done
> Add an article about multiplexing

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .github/workflows/scheduled.yml
Motivation:
NIO is getting stricter concurrency annotations.
This is breaking this project, allow warnings until things settle.
Modifications:
Alter CI flags to allow warnings.
Result:
CI will continue to work for now.
> Allow warnings in CI

- .flake8
- .github/workflows/pull_request.yml
- .licenseignore
Motivation:
More checking is better
Modifications:
Enable and configure flake8
Result:
More CI checks
> Enable python lint in CI

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .github/workflows/scheduled.yml
Motivation:
More testing is better.
Modifications:
Setup github actions to run http/2 spec tests.
Result:
Testing against http/2 spec occurs on pull requests
> Add HTTP/2 spec tests to CI

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
In the async HTTP2 pipeline there is no way to account for the opening and closing of streams. This PR adds a variant of `configureAsyncHTTPServerPipeline` (HTTP2 upgrade channel) that allows the user to pass in a `NIOHTTP2StreamDelegate` to be applied to the HTTP2 channel if the upgrade occurs.
This is similar to #439 which did the same HTTP2 only channels.
> Add a variant of `configureAsyncHTTPServerPipeline` which takes a stream delegate

- Sources/NIOHTTP2/HTTP2ChannelHandler+InboundStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
- Tests/NIOHTTP2Tests/SimpleClientServerInlineStreamMultiplexerTests.swift
Currently, the multiplexer's inbound streams stream is finished only when the channel becomes inactive.
There are some scenarios in which the channel may be closed before it has a chance to become active, and the stream will never be finished. This can cause any users iterating over the stream to hang.
This PR finishes the inbound streams stream when a connection error is fired, and when the handler is removed.
Fewer bugs.
> Finish multiplexer's inbound streams in more cases

- Package.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasLocalSettings.swift
- Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
- Tests/NIOHTTP2Tests/HTTP2ErrorTests.swift
Enable MemberImportVisibility check on all targets. Use a standard string header and footer to bracket the new block for ease of updating in the future with scripts.
> Enable MemberImportVisibility check on all targets

- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
- Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Motivation:
The maximum number of recently reset stream frames to track is limited to a fixed value of 32. This should be configurable.
Modifications:
- Add it to the connection config and propagate it through
Result:
- Resolves #493
> Allow max reset stream frames to be configured

- .github/workflows/pull_request.yml
- IntegrationTests/tests_01_allocation_counters/Thresholds/nightly-6.1.json
Following on from https://github.com/apple/swift-nio-http2/pull/496 delete `Thresholds/nightly-6.1.json` which is no longer needed now that the shared benchmarks workflow has been updated
> Delete Thresholds/nightly-6.1.json symlink

- .github/workflows/main.yml
Update main.yml integration tests to use `swift_test_matrix` as has been done on the PR workflow. This brings it off the deprecated workflow and should fix the nightly-6.1 issue
> Update main.yml integration tests to use swift_test_matrix

- Package.swift
- Sources/NIOHPACK/HPACKErrors.swift
Motivation:
To increase concurrency safety the NIOPHACK module should compile without warning under strict concurrency checking.
Modifications:
- Add explicit Sendable annotations
Result:
No concurrency warnings.
> Strict concurrency for NIOHPACK

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/NIOIsolatedEventLoop+MakeFuture.swift
Motivation:
To increase concurrency safety the NIOHTTP2 module should compile without warning under strict concurrency checking.
Modifications:
- Add a few temporary internal helpers
- Annotate the pipeline helpers
Result:
Fewer concurrency warnings
> Strict concurrency for pipeline helpers

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
To remove all uses of the older workflow so it can be removed to simplify the workflows.
* Switch h2Spec tests to use the newer Swift test matrix workflow, `swift_test_matrix.yml`
This should make no difference to the running of h2Spec tests.
> Switch h2Spec tests to newer Swift test matrix

- Sources/NIOHTTP2/ConnectionStateMachine/StateMachineResult.swift
- Sources/NIOHTTP2/GlitchesMonitor.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2Error.swift
- Sources/NIOHTTP2Server/main.swift
- Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
- Tests/NIOHTTP2Tests/GlitchesMonitorTests.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Add a `GlitchesMonitor` that will terminate a connection if too many stream resets are triggered.
> Add GlitchesMonitor

- Sources/NIOHTTP2/HTTP2ChannelHandler.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Sources/NIOHTTP2/NIOHTTP2FrameDelegate.swift
- Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Motivation:
Frames written from a child channel may not be written immediately by the connection channel. For example, a DATA frame written on a stream may be larger than the max frame size imposed on the connection and so the connection channel will have to slice it into multiple frames. Or the connection may not be writable and may delay the transmission of the frame. This behaviour isn't currently observable but is useful to know about.
Modifications:
- Add a frame delegate which is notified when certain frames are written by the connection channel.
Result:
Users can observer when headers and data frames are written into the connection channel.
> Add a frame delegate
