apple/swift-nio-http2

- CONTRIBUTING.md
> Fix command to generate tests on Linux

- .gitmodules
> Change the submodule URL to use the HTTPS scheme.

- .gitignore
- Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
Adds `HTTPMethod.SOURCE` to `String.init(httpMethod:)`
> add source http method

- Sources/NIOHTTP2/NGHTTP2Session.swift
Context: Our services received (invalid) HTTP2 streams with a disallowed `connection` header. This caused a `nghttp2 error: Invalid HTTP header field was received: frame type: 1, stream: 23, name: [connection], value: [keep-alive]` to be logged, but also caused our serving process to crash subsequently in `onStreamCloseCallback`. After that was worked around, `doOneWrite` was called with a negative length.
This patch does _not_ fix the underlying issue, it only prevents a hard crash of the process until we can migrate to the non-`nghttp2` implementation.
> [nghttp2] Work around two possible crashes.

- Sources/NIOHPACK/StringRing.swift
Motivation:
We use a Bytebuffer as backing storage for a string ringbuffer to avoid
needing to reinvent that data structure ourselves. This used to work great
but NIO 2 recently changed the get* functions to trap if they accessed
memory outside the reader/writer indices.
We were never moving the writer index, instead treating the entire buffer
as valid. This led to preconditions, and sadness.
In an ideal world we'd only mark the bytes that are actually active as
readable to ensure that we have the defensive traps from bytebuffer. In
practice, that's a sufficiently complex thing to do that we're better
served just trusting our code and taking off the guard rails.
In future we should go back to seeing whether a CircularBuffer of strings
will work better, now that Strings are fast. I'll make …
> Mark entire StringRing as readable.

- docker/Dockerfile
- scripts/generate_docs.sh
motivation: publish API docs
changes:
* amend docker file to include jazzy
* add doc generation script based on what we have in swift-nio and swift-log
* fixes #22
> add doc generation script

- README.md
> Fixup typo in README

- README.md
> README: link to API docs

- Sources/NIOHTTP2/HTTP2FrameParser.swift
Motivation:
This is basically a similar issue to #104: we have a CoW data structure (ByteBuffer) in some of
these states, and when calling append on them they force an unnecessary CoW. We can reproduce the
fix from that patch, which is to define an empty state and swap into it before we run the append.
We also define a helper that ensures that we don't screw this up.
Modifications:
- Added new appending state to HTTP2FrameDecoder
- Added helpers for avoiding a CoW
- Avoided CoW in HTTP2FrameDecoder.
Result:
Fewer unnecessary copies
> Avoid CoW when appending inbound frame bytes.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
- Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
Motivation:
Sometimes when you have a hammer everything looks like a nail.
In this case, my hammer was Futures. But we don't need to use a
Future here: these two classes are tightly coupled, and so we can
safely just call from one to the other.
A side note: while this appears to create a reference cycle, the
act of calling the function in question will actually break that
cycle. So it's all good!
Modifications:
- Remove a future callback.
- Have the stream channel hold a reference to the multiplexer.
Result:
Fewer heap allocations.
> Replace Future with a function call.

- IntegrationTests/plugin_echo.sh
- IntegrationTests/plugin_junit_xml.sh
- IntegrationTests/run-single-test.sh
- IntegrationTests/run-tests.sh
- IntegrationTests/test_functions.sh
- IntegrationTests/tests_01_allocation_counters/defines.sh
- IntegrationTests/tests_01_allocation_counters/test_01_allocation_counts.sh
- IntegrationTests/tests_01_allocation_counters/test_01_resources/run-nio-http2-alloc-counter-tests.sh
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_create_client_stream_channel.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_hpack_decoding.swift
- docker/docker-compose.1804.50.yaml
- scripts/integration_tests.sh
Motivation:
Allocation tests are good :).
Modifications:
Add two allocations tests and NIO's integration test framework.
Result:
Hopefully fewer allocations in the future. And better ways to check what
allocations are happening.
> add the first allocation tests for nio-http2

- docker/docker-compose.1804.50.yaml
- docker/docker-compose.yaml
- scripts/analyze_performance_results.rb
motivation: prepare to run performance tests in ci
changes:
add performance-test docker-compose task
add script that can parse the performance test suite results and compare between two result-sets
add generic shell docker-compose task
> add performance analysis docker-compose setup and script

- docker/Dockerfile
- scripts/check_no_api_breakages.sh
motivation: test for api breakage on PR
changes:
* add script to detect api breakage
* amend docker setup to include jq
> api breakage detection

- scripts/build_podspec.sh
> Added Build Podspec Script

- scripts/build_podspec.sh
- scripts/list_topsorted_dependencies.sh
- Update `build_podspec.sh` to leverage updates to the `list_topsorted_dependencies.sh ` script
> Update Build Podspec & Dependencies Script with weissi's Updates

- docker/Dockerfile
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
Unblocks #195 and future work.
> Fixup the docker setup.

- Sources/NIOHTTP2/HTTP2StreamChannel.swift
Motivation:
All public parts of the Channel protocol, such as isActive, are required
to be thread safe. Unfortunately, we missed a spot with the isActive
bool on HTTP2StreamChannel.
Modifications:
Back the HTTP2StreamChannel.isActive bool with an atomic, and set it on
state change.
Result:
Thread-safety for public readers of channel activity
> Make HTTP2StreamChannel.isActive thread safe

- .gitignore
- FuzzTesting/Package.swift
- FuzzTesting/README.md
- FuzzTesting/Sources/FuzzHTTP2/main.swift
- FuzzTesting/do_build.sh
- NOTICE.txt
- scripts/soundness.sh
Motivation:
Fuzzing is great, we should have a good sensible place to centralise a
harness.
Modifications:
- Add a fuzzing harness.
Result:
There's a common way to do fuzzing.
> Add fuzzing harness to swift-nio-http2.

- Sources/NIOHPACK/HPACKDecoder.swift
Motivation
Unnecessary ARC traffic hurts performance
Modifications
Restructure the decodeHeaders function to avoid taking a copy of the
bytebuffer but instead to reset the reader index on error.
Result
One less retain/release on header block decode.
> Remove a retain/release

- scripts/build_podspec.sh
- scripts/list_transitive_dependencies.py
See https://github.com/apple/swift-nio/pull/2082
> Add script to list transitive dependencies

- Package.swift
- Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
- Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
Adopt NIOAsyncChannel.Configuration as the NIO SPI changed
> adopt NIOAsyncChannel.Configuration

- Sources/NIOHTTP2/HTTP2FrameParser.swift
Motivation:
When accumulating sequences of CONTINUATION frames, each frame is parsed from a buffer. These bytes are read when the CONTINUATION frame is parsed, but if more CONTINUATION frames follow then the buffer isn't reset. This means that long sequences of CONTINUATION frames can result in a larger than necessary buffer where most of the contents have already been read.
Modifications:
- Discard the bytes of the accumulation buffer when transitioning back to AccumulatingHeaderBlockFragmentsParserState if more than half of the buffer has been read.
Result:
Lower memory footprint when parsing sequences of CONTINUATION frames.
> Discard read bytes when accumulating continuation frames

- Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
Minor PR to make `configureHTTP2AsyncSecureUpgrade ` helper function public
> Make configureHTTP2AsyncSecureUpgrade public
